/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Fast Data Agent
 * 基于 LangGraph 的 AI 数据分析平台
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse } from 'axios';
import axios from 'axios';

/**
 * 会话描述
 */
export type AnalysisSessionCreateDescription = string | null;

export type AnalysisSessionCreateConfigAnyOf = { [key: string]: unknown };

/**
 * 会话配置
 */
export type AnalysisSessionCreateConfig = AnalysisSessionCreateConfigAnyOf | null;

/**
 * 创建分析会话请求
 */
export interface AnalysisSessionCreate {
  /**
   * 会话名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 会话描述 */
  description?: AnalysisSessionCreateDescription;
  /**
   * 关联的数据源ID列表
   * @minItems 1
   */
  data_source_ids: number[];
  /** 会话配置 */
  config?: AnalysisSessionCreateConfig;
}

/**
 * 会话描述
 */
export type AnalysisSessionDetailDescription = string | null;

/**
 * 关联的数据源ID列表
 */
export type AnalysisSessionDetailDataSourceIds = number[] | null;

export type AnalysisSessionDetailConfigAnyOf = { [key: string]: unknown };

/**
 * 会话配置
 */
export type AnalysisSessionDetailConfig = AnalysisSessionDetailConfigAnyOf | null;

/**
 * 创建时间
 */
export type AnalysisSessionDetailCreateTime = string | null;

/**
 * 更新时间
 */
export type AnalysisSessionDetailUpdateTime = string | null;

/**
 * 分析会话详情（包含数据源信息）
 */
export interface AnalysisSessionDetail {
  /**
   * 会话名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 会话描述 */
  description?: AnalysisSessionDetailDescription;
  /** 会话ID */
  id: number;
  /** 所属用户ID */
  user_id: number;
  /** 关联的数据源ID列表 */
  data_source_ids?: AnalysisSessionDetailDataSourceIds;
  /** 会话配置 */
  config?: AnalysisSessionDetailConfig;
  /** 会话状态 */
  status: string;
  /** 消息数量 */
  message_count?: number;
  /** 创建时间 */
  create_time?: AnalysisSessionDetailCreateTime;
  /** 更新时间 */
  update_time?: AnalysisSessionDetailUpdateTime;
  /** 关联的数据源 */
  data_sources?: DataSourceResponse[];
}

/**
 * 会话描述
 */
export type AnalysisSessionResponseDescription = string | null;

/**
 * 关联的数据源ID列表
 */
export type AnalysisSessionResponseDataSourceIds = number[] | null;

export type AnalysisSessionResponseConfigAnyOf = { [key: string]: unknown };

/**
 * 会话配置
 */
export type AnalysisSessionResponseConfig = AnalysisSessionResponseConfigAnyOf | null;

/**
 * 创建时间
 */
export type AnalysisSessionResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type AnalysisSessionResponseUpdateTime = string | null;

/**
 * 分析会话响应
 */
export interface AnalysisSessionResponse {
  /**
   * 会话名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 会话描述 */
  description?: AnalysisSessionResponseDescription;
  /** 会话ID */
  id: number;
  /** 所属用户ID */
  user_id: number;
  /** 关联的数据源ID列表 */
  data_source_ids?: AnalysisSessionResponseDataSourceIds;
  /** 会话配置 */
  config?: AnalysisSessionResponseConfig;
  /** 会话状态 */
  status: string;
  /** 消息数量 */
  message_count?: number;
  /** 创建时间 */
  create_time?: AnalysisSessionResponseCreateTime;
  /** 更新时间 */
  update_time?: AnalysisSessionResponseUpdateTime;
}

/**
 * 会话名称
 */
export type AnalysisSessionUpdateName = string | null;

/**
 * 会话描述
 */
export type AnalysisSessionUpdateDescription = string | null;

/**
 * 关联的数据源ID列表
 */
export type AnalysisSessionUpdateDataSourceIds = number[] | null;

export type AnalysisSessionUpdateConfigAnyOf = { [key: string]: unknown };

/**
 * 会话配置
 */
export type AnalysisSessionUpdateConfig = AnalysisSessionUpdateConfigAnyOf | null;

/**
 * 更新分析会话请求
 */
export interface AnalysisSessionUpdate {
  /** 会话名称 */
  name?: AnalysisSessionUpdateName;
  /** 会话描述 */
  description?: AnalysisSessionUpdateDescription;
  /** 关联的数据源ID列表 */
  data_source_ids?: AnalysisSessionUpdateDataSourceIds;
  /** 会话配置 */
  config?: AnalysisSessionUpdateConfig;
}

export type BaseResponseAnalysisSessionDetailData = AnalysisSessionDetail | null;

export type BaseResponseAnalysisSessionDetailErr = AnalysisSessionDetail | null;

export interface BaseResponseAnalysisSessionDetail {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseAnalysisSessionDetailData;
  err?: BaseResponseAnalysisSessionDetailErr;
}

export type BaseResponseAnalysisSessionResponseData = AnalysisSessionResponse | null;

export type BaseResponseAnalysisSessionResponseErr = AnalysisSessionResponse | null;

export interface BaseResponseAnalysisSessionResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseAnalysisSessionResponseData;
  err?: BaseResponseAnalysisSessionResponseErr;
}

export type BaseResponseDataSourceResponseData = DataSourceResponse | null;

export type BaseResponseDataSourceResponseErr = DataSourceResponse | null;

export interface BaseResponseDataSourceResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDataSourceResponseData;
  err?: BaseResponseDataSourceResponseErr;
}

export type BaseResponseDataSourceSchemaResponseData = DataSourceSchemaResponse | null;

export type BaseResponseDataSourceSchemaResponseErr = DataSourceSchemaResponse | null;

export interface BaseResponseDataSourceSchemaResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDataSourceSchemaResponseData;
  err?: BaseResponseDataSourceSchemaResponseErr;
}

export type BaseResponseDataSourceTestResultData = DataSourceTestResult | null;

export type BaseResponseDataSourceTestResultErr = DataSourceTestResult | null;

export interface BaseResponseDataSourceTestResult {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDataSourceTestResultData;
  err?: BaseResponseDataSourceTestResultErr;
}

export type BaseResponseFilePreviewResponseData = FilePreviewResponse | null;

export type BaseResponseFilePreviewResponseErr = FilePreviewResponse | null;

export interface BaseResponseFilePreviewResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseFilePreviewResponseData;
  err?: BaseResponseFilePreviewResponseErr;
}

export interface BaseResponseNoneType {
  success: boolean;
  code: number;
  msg: string;
  data?: null;
  err?: null;
}

export type BaseResponsePageResponseAnalysisSessionResponseData = PageResponseAnalysisSessionResponse | null;

export type BaseResponsePageResponseAnalysisSessionResponseErr = PageResponseAnalysisSessionResponse | null;

export interface BaseResponsePageResponseAnalysisSessionResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseAnalysisSessionResponseData;
  err?: BaseResponsePageResponseAnalysisSessionResponseErr;
}

export type BaseResponsePageResponseChatMessageResponseData = PageResponseChatMessageResponse | null;

export type BaseResponsePageResponseChatMessageResponseErr = PageResponseChatMessageResponse | null;

export interface BaseResponsePageResponseChatMessageResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseChatMessageResponseData;
  err?: BaseResponsePageResponseChatMessageResponseErr;
}

export type BaseResponsePageResponseDataSourceResponseData = PageResponseDataSourceResponse | null;

export type BaseResponsePageResponseDataSourceResponseErr = PageResponseDataSourceResponse | null;

export interface BaseResponsePageResponseDataSourceResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseDataSourceResponseData;
  err?: BaseResponsePageResponseDataSourceResponseErr;
}

export type BaseResponsePageResponseTaskRecommendationResponseData = PageResponseTaskRecommendationResponse | null;

export type BaseResponsePageResponseTaskRecommendationResponseErr = PageResponseTaskRecommendationResponse | null;

export interface BaseResponsePageResponseTaskRecommendationResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseTaskRecommendationResponseData;
  err?: BaseResponsePageResponseTaskRecommendationResponseErr;
}

export type BaseResponsePageResponseUploadedFileResponseData = PageResponseUploadedFileResponse | null;

export type BaseResponsePageResponseUploadedFileResponseErr = PageResponseUploadedFileResponse | null;

export interface BaseResponsePageResponseUploadedFileResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseUploadedFileResponseData;
  err?: BaseResponsePageResponseUploadedFileResponseErr;
}

export type BaseResponsePageResponseUserResponseData = PageResponseUserResponse | null;

export type BaseResponsePageResponseUserResponseErr = PageResponseUserResponse | null;

export interface BaseResponsePageResponseUserResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseUserResponseData;
  err?: BaseResponsePageResponseUserResponseErr;
}

export type BaseResponseTaskRecommendationResponseData = TaskRecommendationResponse | null;

export type BaseResponseTaskRecommendationResponseErr = TaskRecommendationResponse | null;

export interface BaseResponseTaskRecommendationResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseTaskRecommendationResponseData;
  err?: BaseResponseTaskRecommendationResponseErr;
}

export type BaseResponseTokenData = Token | null;

export type BaseResponseTokenErr = Token | null;

export interface BaseResponseToken {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseTokenData;
  err?: BaseResponseTokenErr;
}

export type BaseResponseUploadedFileResponseData = UploadedFileResponse | null;

export type BaseResponseUploadedFileResponseErr = UploadedFileResponse | null;

export interface BaseResponseUploadedFileResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseUploadedFileResponseData;
  err?: BaseResponseUploadedFileResponseErr;
}

export type BaseResponseUserResponseData = UserResponse | null;

export type BaseResponseUserResponseErr = UserResponse | null;

export interface BaseResponseUserResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseUserResponseData;
  err?: BaseResponseUserResponseErr;
}

export type BaseResponseDictStrAnyDataAnyOf = { [key: string]: unknown };

export type BaseResponseDictStrAnyData = BaseResponseDictStrAnyDataAnyOf | null;

export type BaseResponseDictStrAnyErrAnyOf = { [key: string]: unknown };

export type BaseResponseDictStrAnyErr = BaseResponseDictStrAnyErrAnyOf | null;

export interface BaseResponseDictStrAny {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDictStrAnyData;
  err?: BaseResponseDictStrAnyErr;
}

export type BaseResponseIntData = number | null;

export type BaseResponseIntErr = number | null;

export interface BaseResponseInt {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseIntData;
  err?: BaseResponseIntErr;
}

export type BaseResponseListTaskRecommendationResponseData = TaskRecommendationResponse[] | null;

export type BaseResponseListTaskRecommendationResponseErr = TaskRecommendationResponse[] | null;

export interface BaseResponseListTaskRecommendationResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseListTaskRecommendationResponseData;
  err?: BaseResponseListTaskRecommendationResponseErr;
}

export type BaseResponseStrData = string | null;

export type BaseResponseStrErr = string | null;

export interface BaseResponseStr {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseStrData;
  err?: BaseResponseStrErr;
}

export interface BodyUploadFileApiV1FilesUploadPost {
  /** 要上传的文件 */
  file: Blob;
}

export interface BodyUploadSessionFileApiV1SessionsSessionIdFilesUploadPost {
  file: Blob;
}

/**
 * 创建对话消息请求（用户发送）
 */
export interface ChatMessageCreate {
  /**
   * 消息内容
   * @minLength 1
   */
  content: string;
}

/**
 * LangChain 消息ID
 */
export type ChatMessageResponseMessageId = string | null;

/**
 * 消息名称
 */
export type ChatMessageResponseName = string | null;

export type ChatMessageResponseToolCallsAnyOfItem = { [key: string]: unknown };

/**
 * 工具调用列表
 */
export type ChatMessageResponseToolCalls = ChatMessageResponseToolCallsAnyOfItem[] | null;

export type ChatMessageResponseUsageMetadataAnyOf = { [key: string]: unknown };

/**
 * Token使用统计
 */
export type ChatMessageResponseUsageMetadata = ChatMessageResponseUsageMetadataAnyOf | null;

/**
 * 工具调用ID
 */
export type ChatMessageResponseToolCallId = string | null;

export type ChatMessageResponseArtifactAnyOf = { [key: string]: unknown };

/**
 * 工具产出物(图表、表格等)
 */
export type ChatMessageResponseArtifact = ChatMessageResponseArtifactAnyOf | null;

/**
 * 创建时间
 */
export type ChatMessageResponseCreateTime = string | null;

/**
 * 对话消息响应 - 与 LangChain 消息格式对齐
 */
export interface ChatMessageResponse {
  /** 消息ID */
  id: number;
  /** 所属会话ID */
  session_id: number;
  /** 消息类型: human/ai/system/tool */
  message_type: string;
  /** 消息内容 */
  content: string;
  /** LangChain 消息ID */
  message_id?: ChatMessageResponseMessageId;
  /** 消息名称 */
  name?: ChatMessageResponseName;
  /** 工具调用列表 */
  tool_calls?: ChatMessageResponseToolCalls;
  /** Token使用统计 */
  usage_metadata?: ChatMessageResponseUsageMetadata;
  /** 工具调用ID */
  tool_call_id?: ChatMessageResponseToolCallId;
  /** 工具产出物(图表、表格等) */
  artifact?: ChatMessageResponseArtifact;
  /** 创建时间 */
  create_time?: ChatMessageResponseCreateTime;
}

/**
 * 列注释
 */
export type ColumnSchemaComment = string | null;

/**
 * 列结构
 */
export interface ColumnSchema {
  /** 列名 */
  name: string;
  /** 数据类型 */
  data_type: string;
  /** 是否可空 */
  nullable?: boolean;
  /** 是否主键 */
  primary_key?: boolean;
  /** 列注释 */
  comment?: ColumnSchemaComment;
}

/**
 * 数据源描述
 */
export type DataSourceCreateDescription = string | null;

/**
 * 数据源分组名称
 */
export type DataSourceCreateGroupName = string | null;

/**
 * 数据库连接配置
 */
export type DataSourceCreateDbConfig = DatabaseConnectionConfig | null;

/**
 * 关联的上传文件ID
 */
export type DataSourceCreateFileId = number | null;

/**
 * 创建数据源请求
 */
export interface DataSourceCreate {
  /**
   * 数据源名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 数据源描述 */
  description?: DataSourceCreateDescription;
  source_type?: DataSourceType;
  /** 数据源分组名称 */
  group_name?: DataSourceCreateGroupName;
  /** 数据库连接配置 */
  db_config?: DataSourceCreateDbConfig;
  /** 关联的上传文件ID */
  file_id?: DataSourceCreateFileId;
}

/**
 * 数据源描述
 */
export type DataSourceResponseDescription = string | null;

/**
 * 数据源分组名称
 */
export type DataSourceResponseGroupName = string | null;

/**
 * 数据库类型
 */
export type DataSourceResponseDbType = DatabaseType | null;

/**
 * 数据库主机
 */
export type DataSourceResponseHost = string | null;

/**
 * 数据库端口
 */
export type DataSourceResponsePort = number | null;

/**
 * 数据库名
 */
export type DataSourceResponseDatabase = string | null;

/**
 * 用户名
 */
export type DataSourceResponseUsername = string | null;

/**
 * 关联的上传文件ID
 */
export type DataSourceResponseFileId = number | null;

export type DataSourceResponseSchemaCacheAnyOf = { [key: string]: unknown };

/**
 * 表结构缓存
 */
export type DataSourceResponseSchemaCache = DataSourceResponseSchemaCacheAnyOf | null;

/**
 * 创建时间
 */
export type DataSourceResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type DataSourceResponseUpdateTime = string | null;

/**
 * 数据源响应
 */
export interface DataSourceResponse {
  /**
   * 数据源名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 数据源描述 */
  description?: DataSourceResponseDescription;
  source_type?: DataSourceType;
  /** 数据源分组名称 */
  group_name?: DataSourceResponseGroupName;
  /** 数据源ID */
  id: number;
  /** 所属用户ID */
  user_id: number;
  /** 数据库类型 */
  db_type?: DataSourceResponseDbType;
  /** 数据库主机 */
  host?: DataSourceResponseHost;
  /** 数据库端口 */
  port?: DataSourceResponsePort;
  /** 数据库名 */
  database?: DataSourceResponseDatabase;
  /** 用户名 */
  username?: DataSourceResponseUsername;
  /** 关联的上传文件ID */
  file_id?: DataSourceResponseFileId;
  /** 表结构缓存 */
  schema_cache?: DataSourceResponseSchemaCache;
  /** 创建时间 */
  create_time?: DataSourceResponseCreateTime;
  /** 更新时间 */
  update_time?: DataSourceResponseUpdateTime;
}

/**
 * 同步时间
 */
export type DataSourceSchemaResponseSyncedAt = string | null;

/**
 * 数据源 Schema 响应
 */
export interface DataSourceSchemaResponse {
  /** 表列表 */
  tables?: TableSchema[];
  /** 同步时间 */
  synced_at?: DataSourceSchemaResponseSyncedAt;
}

/**
 * 连接延迟（毫秒）
 */
export type DataSourceTestResultLatencyMs = number | null;

/**
 * 数据源连接测试结果
 */
export interface DataSourceTestResult {
  /** 是否连接成功 */
  success: boolean;
  /** 测试结果消息 */
  message: string;
  /** 连接延迟（毫秒） */
  latency_ms?: DataSourceTestResultLatencyMs;
}

/**
 * 数据源类型
 */
export type DataSourceType = (typeof DataSourceType)[keyof typeof DataSourceType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataSourceType = {
  database: 'database',
  file: 'file',
} as const;

/**
 * 数据源名称
 */
export type DataSourceUpdateName = string | null;

/**
 * 数据源描述
 */
export type DataSourceUpdateDescription = string | null;

/**
 * 数据源分组名称
 */
export type DataSourceUpdateGroupName = string | null;

/**
 * 数据库连接配置
 */
export type DataSourceUpdateDbConfig = DatabaseConnectionConfig | null;

/**
 * 更新数据源请求
 */
export interface DataSourceUpdate {
  /** 数据源名称 */
  name?: DataSourceUpdateName;
  /** 数据源描述 */
  description?: DataSourceUpdateDescription;
  /** 数据源分组名称 */
  group_name?: DataSourceUpdateGroupName;
  /** 数据库连接配置 */
  db_config?: DataSourceUpdateDbConfig;
}

export type DatabaseConnectionConfigExtraParamsAnyOf = { [key: string]: unknown };

/**
 * 额外连接参数
 */
export type DatabaseConnectionConfigExtraParams = DatabaseConnectionConfigExtraParamsAnyOf | null;

/**
 * 数据库连接配置
 */
export interface DatabaseConnectionConfig {
  db_type: DatabaseType;
  /**
   * 数据库主机
   * @minLength 1
   * @maxLength 255
   */
  host: string;
  /**
   * 数据库端口
   * @minimum 1
   * @maximum 65535
   */
  port: number;
  /**
   * 数据库名
   * @minLength 1
   * @maxLength 100
   */
  database: string;
  /**
   * 用户名
   * @minLength 1
   * @maxLength 100
   */
  username: string;
  /**
   * 密码
   * @minLength 1
   * @maxLength 255
   */
  password: string;
  /** 额外连接参数 */
  extra_params?: DatabaseConnectionConfigExtraParams;
}

/**
 * 数据库类型
 */
export type DatabaseType = (typeof DatabaseType)[keyof typeof DatabaseType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatabaseType = {
  mysql: 'mysql',
  postgresql: 'postgresql',
  sqlite: 'sqlite',
} as const;

export type FilePreviewResponseColumnsItem = { [key: string]: unknown };

export type FilePreviewResponseDataItem = { [key: string]: unknown };

/**
 * 文件预览响应
 */
export interface FilePreviewResponse {
  /** 列信息 */
  columns: FilePreviewResponseColumnsItem[];
  /** 预览数据 */
  data: FilePreviewResponseDataItem[];
  /** 总行数 */
  total_rows: number;
}

/**
 * 文件类型
 */
export type FileType = (typeof FileType)[keyof typeof FileType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileType = {
  csv: 'csv',
  excel: 'excel',
  json: 'json',
  parquet: 'parquet',
  sqlite: 'sqlite',
} as const;

export type GenerateFollowupRequestLastResultAnyOf = { [key: string]: unknown };

/**
 * 上次分析结果
 */
export type GenerateFollowupRequestLastResult = GenerateFollowupRequestLastResultAnyOf | null;

/**
 * 触发消息ID
 */
export type GenerateFollowupRequestTriggerMessageId = number | null;

/**
 * 生成追问推荐请求
 */
export interface GenerateFollowupRequest {
  /** 对话上下文 */
  conversation_context: string;
  /** 上次分析结果 */
  last_result?: GenerateFollowupRequestLastResult;
  /**
   * 最大推荐数量
   * @minimum 1
   * @maximum 5
   */
  max_count?: number;
  /** 触发消息ID */
  trigger_message_id?: GenerateFollowupRequestTriggerMessageId;
}

/**
 * 生成推荐请求
 */
export interface GenerateRecommendationsRequest {
  /**
   * 最大推荐数量
   * @minimum 1
   * @maximum 10
   */
  max_count?: number;
  /** 是否强制重新生成（会清理现有pending推荐） */
  force_regenerate?: boolean;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * 登录请求
 */
export interface LoginRequest {
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /**
   * 密码
   * @minLength 6
   * @maxLength 128
   */
  password: string;
}

export interface PageResponseAnalysisSessionResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: AnalysisSessionResponse[];
}

export interface PageResponseChatMessageResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: ChatMessageResponse[];
}

export interface PageResponseDataSourceResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: DataSourceResponse[];
}

export interface PageResponseTaskRecommendationResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: TaskRecommendationResponse[];
}

export interface PageResponseUploadedFileResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: UploadedFileResponse[];
}

export interface PageResponseUserResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: UserResponse[];
}

/**
 * 修改密码请求
 */
export interface PasswordChange {
  /**
   * 旧密码
   * @minLength 6
   * @maxLength 128
   */
  old_password: string;
  /**
   * 新密码
   * @minLength 6
   * @maxLength 128
   */
  new_password: string;
}

/**
 * 刷新令牌请求
 */
export interface RefreshTokenRequest {
  /** 刷新令牌 */
  refresh_token: string;
}

/**
 * 行数（估算）
 */
export type TableSchemaRowCount = number | null;

/**
 * 表注释
 */
export type TableSchemaComment = string | null;

/**
 * 表结构
 */
export interface TableSchema {
  /** 表名 */
  name: string;
  /** 列信息 */
  columns?: ColumnSchema[];
  /** 行数（估算） */
  row_count?: TableSchemaRowCount;
  /** 表注释 */
  comment?: TableSchemaComment;
}

export type TaskRecommendationResponseDescription = string | null;

export type TaskRecommendationResponseTriggerMessageId = number | null;

/**
 * 推荐响应
 */
export interface TaskRecommendationResponse {
  id: number;
  session_id: number;
  title: string;
  description: TaskRecommendationResponseDescription;
  category: string;
  source_type: string;
  priority: number;
  status: string;
  trigger_message_id: TaskRecommendationResponseTriggerMessageId;
  create_time: string;
  update_time: string;
}

/**
 * 更新推荐
 */
export interface TaskRecommendationUpdate {
  /** 状态：pending/selected/dismissed */
  status: string;
}

/**
 * Token基础数据
 */
export interface Token {
  id: number;
  nickname: string;
  access_token: string;
  refresh_token: string;
  token_type?: string;
}

/**
 * MIME类型
 */
export type UploadedFileResponseMimeType = string | null;

/**
 * 数据行数
 */
export type UploadedFileResponseRowCount = number | null;

/**
 * 数据列数
 */
export type UploadedFileResponseColumnCount = number | null;

export type UploadedFileResponseColumnsInfoAnyOfItem = { [key: string]: unknown };

/**
 * 列信息
 */
export type UploadedFileResponseColumnsInfo = UploadedFileResponseColumnsInfoAnyOfItem[] | null;

/**
 * 错误信息
 */
export type UploadedFileResponseErrorMessage = string | null;

/**
 * 创建时间
 */
export type UploadedFileResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type UploadedFileResponseUpdateTime = string | null;

/**
 * 上传文件响应
 */
export interface UploadedFileResponse {
  /** 文件ID */
  id: number;
  /** 上传用户ID */
  user_id: number;
  /** 原始文件名 */
  original_name: string;
  /** MinIO对象存储Key */
  object_key: string;
  file_type: FileType;
  /** 文件大小(字节) */
  file_size: number;
  /** MIME类型 */
  mime_type?: UploadedFileResponseMimeType;
  /** 数据行数 */
  row_count?: UploadedFileResponseRowCount;
  /** 数据列数 */
  column_count?: UploadedFileResponseColumnCount;
  /** 列信息 */
  columns_info?: UploadedFileResponseColumnsInfo;
  /** 处理状态 */
  status: string;
  /** 错误信息 */
  error_message?: UploadedFileResponseErrorMessage;
  /** 创建时间 */
  create_time?: UploadedFileResponseCreateTime;
  /** 更新时间 */
  update_time?: UploadedFileResponseUpdateTime;
}

/**
 * 创建用户请求
 */
export interface UserCreate {
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** 邮箱 */
  email: string;
  /**
   * 昵称
   * @minLength 1
   * @maxLength 50
   */
  nickname: string;
  /**
   * 密码
   * @minLength 6
   * @maxLength 128
   */
  password: string;
  /** 是否激活 */
  is_active?: boolean;
  /** 是否超级管理员 */
  is_superuser?: boolean;
}

/**
 * 创建时间
 */
export type UserResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type UserResponseUpdateTime = string | null;

/**
 * 用户响应
 */
export interface UserResponse {
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** 邮箱 */
  email: string;
  /**
   * 昵称
   * @minLength 1
   * @maxLength 50
   */
  nickname: string;
  /** 用户ID */
  id: number;
  /** 是否激活 */
  is_active: boolean;
  /** 是否超级管理员 */
  is_superuser: boolean;
  /** 创建时间 */
  create_time?: UserResponseCreateTime;
  /** 更新时间 */
  update_time?: UserResponseUpdateTime;
}

/**
 * 邮箱
 */
export type UserUpdateEmail = string | null;

/**
 * 昵称
 */
export type UserUpdateNickname = string | null;

/**
 * 是否激活
 */
export type UserUpdateIsActive = boolean | null;

/**
 * 是否超级管理员
 */
export type UserUpdateIsSuperuser = boolean | null;

/**
 * 更新用户请求
 */
export interface UserUpdate {
  /** 邮箱 */
  email?: UserUpdateEmail;
  /** 昵称 */
  nickname?: UserUpdateNickname;
  /** 是否激活 */
  is_active?: UserUpdateIsActive;
  /** 是否超级管理员 */
  is_superuser?: UserUpdateIsSuperuser;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GetUsersApiV1UsersGetParams = {
  /**
   * @minimum 1
   */
  page_num?: number;
  /**
   * @minimum 1
   */
  page_size?: number;
  keyword?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
};

export type GetDataSourcesApiV1DataSourcesGetParams = {
  /**
   * @minimum 1
   */
  page_num?: number;
  /**
   * @minimum 1
   */
  page_size?: number;
  keyword?: string | null;
  source_type?: DataSourceType | null;
};

export type GetFilesApiV1FilesGetParams = {
  /**
   * @minimum 1
   */
  page_num?: number;
  /**
   * @minimum 1
   */
  page_size?: number;
  keyword?: string | null;
  file_type?: FileType | null;
  status?: string | null;
};

export type GetFilePreviewApiV1FilesFileIdPreviewGetParams = {
  rows?: number;
};

export type GetDownloadUrlApiV1FilesFileIdDownloadUrlGetParams = {
  expires?: number;
};

export type GetSessionsApiV1SessionsGetParams = {
  /**
   * @minimum 1
   */
  page_num?: number;
  /**
   * @minimum 1
   */
  page_size?: number;
  keyword?: string | null;
  status?: string | null;
};

export type GetMessagesApiV1SessionsSessionIdMessagesGetParams = {
  /**
   * @minimum 1
   */
  page_num?: number;
  /**
   * @minimum 1
   */
  page_size?: number;
};

export type GetRecommendationsApiV1SessionsSessionIdRecommendationsGetParams = {
  status_filter?: string | null;
  source_type?: string | null;
  /**
   * @minimum 1
   */
  page_num?: number;
  /**
   * @minimum 1
   */
  page_size?: number;
};

export type GenerateRecommendationsApiV1SessionsSessionIdRecommendationsPostBody =
  GenerateRecommendationsRequest | null;

export type DismissAllRecommendationsApiV1SessionsSessionIdRecommendationsDeleteParams = {
  source_type?: string | null;
};

/**
 * 根路径，健康检查
 * @summary Root
 */
export const rootGet = <TData = AxiosResponse<unknown>>(options?: AxiosRequestConfig): Promise<TData> => {
  return axios.get('/', options);
};

/**
 * 健康检查接口
 * @summary Health Check
 */
export const healthCheckHealthGet = <TData = AxiosResponse<unknown>>(options?: AxiosRequestConfig): Promise<TData> => {
  return axios.get('/health', options);
};

/**
 * 用户登录
 * @summary Login
 */
export const loginApiV1AuthLoginPost = <TData = AxiosResponse<BaseResponseToken>>(
  loginRequest: LoginRequest,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post('/api/v1/auth/login', loginRequest, options);
};

/**
 * 刷新访问令牌
 * @summary Refresh Token
 */
export const refreshTokenApiV1AuthRefreshPost = <TData = AxiosResponse<BaseResponseToken>>(
  refreshTokenRequest: RefreshTokenRequest,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post('/api/v1/auth/refresh', refreshTokenRequest, options);
};

/**
 * 用户注册
 * @summary Register
 */
export const registerApiV1AuthRegisterPost = <TData = AxiosResponse<BaseResponseUserResponse>>(
  userCreate: UserCreate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post('/api/v1/auth/register', userCreate, options);
};

/**
 * 获取当前登录用户信息
 * @summary Get Current User Info
 */
export const getCurrentUserInfoApiV1AuthMeGet = <TData = AxiosResponse<BaseResponseUserResponse>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get('/api/v1/auth/me', options);
};

/**
 * 更新当前登录用户信息
 * @summary Update Current User
 */
export const updateCurrentUserApiV1AuthMePut = <TData = AxiosResponse<BaseResponseUserResponse>>(
  userUpdate: UserUpdate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.put('/api/v1/auth/me', userUpdate, options);
};

/**
 * 修改密码
 * @summary Change Password
 */
export const changePasswordApiV1AuthChangePasswordPost = <TData = AxiosResponse<BaseResponseNoneType>>(
  passwordChange: PasswordChange,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post('/api/v1/auth/change-password', passwordChange, options);
};

/**
 * 获取用户列表（分页）- 需要超级管理员权限
 * @summary Get Users
 */
export const getUsersApiV1UsersGet = <TData = AxiosResponse<BaseResponsePageResponseUserResponse>>(
  params?: GetUsersApiV1UsersGetParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get('/api/v1/users', {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * 创建新用户 - 需要超级管理员权限
 * @summary Create User
 */
export const createUserApiV1UsersPost = <TData = AxiosResponse<BaseResponseUserResponse>>(
  userCreate: UserCreate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post('/api/v1/users', userCreate, options);
};

/**
 * 获取单个用户详情 - 需要超级管理员权限
 * @summary Get User
 */
export const getUserApiV1UsersUserIdGet = <TData = AxiosResponse<BaseResponseUserResponse>>(
  userId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/users/${userId}`, options);
};

/**
 * 更新用户信息 - 需要超级管理员权限
 * @summary Update User
 */
export const updateUserApiV1UsersUserIdPut = <TData = AxiosResponse<BaseResponseUserResponse>>(
  userId: number,
  userUpdate: UserUpdate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.put(`/api/v1/users/${userId}`, userUpdate, options);
};

/**
 * 删除用户（逻辑删除）- 需要超级管理员权限
 * @summary Delete User
 */
export const deleteUserApiV1UsersUserIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
  userId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/api/v1/users/${userId}`, options);
};

/**
 * 获取数据源列表（分页）
 * @summary Get Data Sources
 */
export const getDataSourcesApiV1DataSourcesGet = <TData = AxiosResponse<BaseResponsePageResponseDataSourceResponse>>(
  params?: GetDataSourcesApiV1DataSourcesGetParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get('/api/v1/data-sources', {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * 创建数据源
 * @summary Create Data Source
 */
export const createDataSourceApiV1DataSourcesPost = <TData = AxiosResponse<BaseResponseDataSourceResponse>>(
  dataSourceCreate: DataSourceCreate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post('/api/v1/data-sources', dataSourceCreate, options);
};

/**
 * 获取单个数据源详情
 * @summary Get Data Source
 */
export const getDataSourceApiV1DataSourcesDataSourceIdGet = <TData = AxiosResponse<BaseResponseDataSourceResponse>>(
  dataSourceId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/data-sources/${dataSourceId}`, options);
};

/**
 * 更新数据源
 * @summary Update Data Source
 */
export const updateDataSourceApiV1DataSourcesDataSourceIdPut = <TData = AxiosResponse<BaseResponseDataSourceResponse>>(
  dataSourceId: number,
  dataSourceUpdate: DataSourceUpdate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.put(`/api/v1/data-sources/${dataSourceId}`, dataSourceUpdate, options);
};

/**
 * 删除数据源
 * @summary Delete Data Source
 */
export const deleteDataSourceApiV1DataSourcesDataSourceIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
  dataSourceId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/api/v1/data-sources/${dataSourceId}`, options);
};

/**
 * 测试数据源连接
 * @summary Test Data Source Connection
 */
export const testDataSourceConnectionApiV1DataSourcesDataSourceIdTestPost = <
  TData = AxiosResponse<BaseResponseDataSourceTestResult>,
>(
  dataSourceId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/v1/data-sources/${dataSourceId}/test`, undefined, options);
};

/**
 * 同步数据源 Schema
 * @summary Sync Data Source Schema
 */
export const syncDataSourceSchemaApiV1DataSourcesDataSourceIdSyncSchemaPost = <
  TData = AxiosResponse<BaseResponseDataSourceSchemaResponse>,
>(
  dataSourceId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/v1/data-sources/${dataSourceId}/sync-schema`, undefined, options);
};

/**
 * 获取数据源 Schema（从缓存）
 * @summary Get Data Source Schema
 */
export const getDataSourceSchemaApiV1DataSourcesDataSourceIdSchemaGet = <
  TData = AxiosResponse<BaseResponseDataSourceSchemaResponse>,
>(
  dataSourceId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/data-sources/${dataSourceId}/schema`, options);
};

/**
 * 获取文件列表（分页）
 * @summary Get Files
 */
export const getFilesApiV1FilesGet = <TData = AxiosResponse<BaseResponsePageResponseUploadedFileResponse>>(
  params?: GetFilesApiV1FilesGetParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get('/api/v1/files', {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * 获取单个文件详情
 * @summary Get File
 */
export const getFileApiV1FilesFileIdGet = <TData = AxiosResponse<BaseResponseUploadedFileResponse>>(
  fileId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/files/${fileId}`, options);
};

/**
 * 删除文件
 * @summary Delete File
 */
export const deleteFileApiV1FilesFileIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
  fileId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/api/v1/files/${fileId}`, options);
};

/**
 * 上传文件
 * @summary Upload File
 */
export const uploadFileApiV1FilesUploadPost = <TData = AxiosResponse<BaseResponseUploadedFileResponse>>(
  bodyUploadFileApiV1FilesUploadPost: BodyUploadFileApiV1FilesUploadPost,
  options?: AxiosRequestConfig
): Promise<TData> => {
  const formData = new FormData();
  formData.append('file', bodyUploadFileApiV1FilesUploadPost.file);

  return axios.post('/api/v1/files/upload', formData, options);
};

/**
 * 获取文件预览
 * @summary Get File Preview
 */
export const getFilePreviewApiV1FilesFileIdPreviewGet = <TData = AxiosResponse<BaseResponseFilePreviewResponse>>(
  fileId: number,
  params?: GetFilePreviewApiV1FilesFileIdPreviewGetParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/files/${fileId}/preview`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * 获取文件下载 URL
 * @summary Get Download Url
 */
export const getDownloadUrlApiV1FilesFileIdDownloadUrlGet = <TData = AxiosResponse<BaseResponseStr>>(
  fileId: number,
  params?: GetDownloadUrlApiV1FilesFileIdDownloadUrlGetParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/files/${fileId}/download-url`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * 获取会话列表（分页）
 * @summary Get Sessions
 */
export const getSessionsApiV1SessionsGet = <TData = AxiosResponse<BaseResponsePageResponseAnalysisSessionResponse>>(
  params?: GetSessionsApiV1SessionsGetParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get('/api/v1/sessions', {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * 创建会话
 * @summary Create Session
 */
export const createSessionApiV1SessionsPost = <TData = AxiosResponse<BaseResponseAnalysisSessionResponse>>(
  analysisSessionCreate: AnalysisSessionCreate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post('/api/v1/sessions', analysisSessionCreate, options);
};

/**
 * 获取单个会话详情（包含数据源信息）
 * @summary Get Session
 */
export const getSessionApiV1SessionsSessionIdGet = <TData = AxiosResponse<BaseResponseAnalysisSessionDetail>>(
  sessionId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/sessions/${sessionId}`, options);
};

/**
 * 更新会话
 * @summary Update Session
 */
export const updateSessionApiV1SessionsSessionIdPut = <TData = AxiosResponse<BaseResponseAnalysisSessionResponse>>(
  sessionId: number,
  analysisSessionUpdate: AnalysisSessionUpdate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.put(`/api/v1/sessions/${sessionId}`, analysisSessionUpdate, options);
};

/**
 * 删除会话
 * @summary Delete Session
 */
export const deleteSessionApiV1SessionsSessionIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
  sessionId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/api/v1/sessions/${sessionId}`, options);
};

/**
 * 归档会话
 * @summary Archive Session
 */
export const archiveSessionApiV1SessionsSessionIdArchivePost = <
  TData = AxiosResponse<BaseResponseAnalysisSessionResponse>,
>(
  sessionId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/v1/sessions/${sessionId}/archive`, undefined, options);
};

/**
 * 上传文件到会话目录

用于上传临时数据文件供 AI 分析使用。
文件会保存到沙盒的会话目录中。
 * @summary Upload Session File
 */
export const uploadSessionFileApiV1SessionsSessionIdFilesUploadPost = <TData = AxiosResponse<BaseResponseDictStrAny>>(
  sessionId: number,
  bodyUploadSessionFileApiV1SessionsSessionIdFilesUploadPost: BodyUploadSessionFileApiV1SessionsSessionIdFilesUploadPost,
  options?: AxiosRequestConfig
): Promise<TData> => {
  const formData = new FormData();
  formData.append('file', bodyUploadSessionFileApiV1SessionsSessionIdFilesUploadPost.file);

  return axios.post(`/api/v1/sessions/${sessionId}/files/upload`, formData, options);
};

/**
 * 列出会话文件

返回会话目录中的所有文件，包括：
- 用户上传的数据文件
- SQL 查询结果的 parquet 缓存
- 生成的图表文件
- 其他分析过程中产生的文件
 * @summary List Session Files
 */
export const listSessionFilesApiV1SessionsSessionIdFilesGet = <TData = AxiosResponse<BaseResponseDictStrAny>>(
  sessionId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/sessions/${sessionId}/files`, options);
};

/**
 * 下载会话文件

Args:
    session_id: 会话 ID
    filename: 文件名（相对于会话目录的路径）
 * @summary Download Session File
 */
export const downloadSessionFileApiV1SessionsSessionIdFilesFilenameGet = <TData = AxiosResponse<unknown>>(
  sessionId: number,
  filename: string,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/sessions/${sessionId}/files/${filename}`, options);
};

/**
 * 发送消息并获取 AI 响应（SSE 流式）

兼容 Vercel AI SDK useChat hook，使用 Data Stream Protocol。

## 流协议

使用 SSE `data:` 格式，通过 JSON 的 `type` 字段区分事件类型。

### 消息开始
```
data: {"type":"start","messageId":"msg_xxx"}
```

### 文本流 (start/delta/end 模式)
```
data: {"type":"text-start","id":"text_xxx"}
data: {"type":"text-delta","id":"text_xxx","delta":"你好"}
data: {"type":"text-end","id":"text_xxx"}
```

### 工具调用
```
data: {"type":"tool-input-start","toolCallId":"call_xxx","toolName":"execute_sql"}
data: {"type":"tool-input-available","toolCallId":"call_xxx","toolName":"execute_sql","input":{...}}
```

### 工具结果
```
data: {"type":"tool-output-available","toolCallId":"call_xxx","output":{...},"artifact":{...}}
```

### 步骤控制
```
data: {"type":"start-step"}
data: {"type":"finish-step"}
data: {"type":"finish"}
```

### 错误
```
data: {"type":"error","errorText":"..."}
```

### 流结束
```
data: [DONE]
```

参考: https://ai-sdk.dev/docs/ai-sdk-ui/stream-protocol
 * @summary Chat
 */
export const chatApiV1SessionsSessionIdChatPost = <TData = AxiosResponse<void>>(
  sessionId: number,
  chatMessageCreate: ChatMessageCreate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/v1/sessions/${sessionId}/chat`, chatMessageCreate, options);
};

/**
 * 获取会话的历史消息（分页）

返回消息列表，按创建时间升序排列
 * @summary Get Messages
 */
export const getMessagesApiV1SessionsSessionIdMessagesGet = <
  TData = AxiosResponse<BaseResponsePageResponseChatMessageResponse>,
>(
  sessionId: number,
  params?: GetMessagesApiV1SessionsSessionIdMessagesGetParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/sessions/${sessionId}/messages`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * 清空会话的所有消息
 * @summary Clear Messages
 */
export const clearMessagesApiV1SessionsSessionIdMessagesDelete = <TData = AxiosResponse<BaseResponseInt>>(
  sessionId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/api/v1/sessions/${sessionId}/messages`, options);
};

/**
 * 获取会话的推荐列表（分页）
 * @summary Get Recommendations
 */
export const getRecommendationsApiV1SessionsSessionIdRecommendationsGet = <
  TData = AxiosResponse<BaseResponsePageResponseTaskRecommendationResponse>,
>(
  sessionId: number,
  params?: GetRecommendationsApiV1SessionsSessionIdRecommendationsGetParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/v1/sessions/${sessionId}/recommendations`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * 生成初始任务推荐

基于会话关联的数据源 Schema 生成分析任务推荐
 * @summary Generate Recommendations
 */
export const generateRecommendationsApiV1SessionsSessionIdRecommendationsPost = <
  TData = AxiosResponse<BaseResponseListTaskRecommendationResponse>,
>(
  sessionId: number,
  generateRecommendationsApiV1SessionsSessionIdRecommendationsPostBody: GenerateRecommendationsApiV1SessionsSessionIdRecommendationsPostBody,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(
    `/api/v1/sessions/${sessionId}/recommendations`,
    generateRecommendationsApiV1SessionsSessionIdRecommendationsPostBody,
    options
  );
};

/**
 * 批量忽略会话中的待选择推荐
 * @summary Dismiss All Recommendations
 */
export const dismissAllRecommendationsApiV1SessionsSessionIdRecommendationsDelete = <
  TData = AxiosResponse<BaseResponseNoneType>,
>(
  sessionId: number,
  params?: DismissAllRecommendationsApiV1SessionsSessionIdRecommendationsDeleteParams,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/api/v1/sessions/${sessionId}/recommendations`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * 生成追问推荐

基于对话上下文生成追问建议
 * @summary Generate Followup Recommendations
 */
export const generateFollowupRecommendationsApiV1SessionsSessionIdRecommendationsFollowupPost = <
  TData = AxiosResponse<BaseResponseListTaskRecommendationResponse>,
>(
  sessionId: number,
  generateFollowupRequest: GenerateFollowupRequest,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/v1/sessions/${sessionId}/recommendations/followup`, generateFollowupRequest, options);
};

/**
 * 更新推荐状态
 * @summary Update Recommendation
 */
export const updateRecommendationApiV1SessionsSessionIdRecommendationsRecommendationIdPut = <
  TData = AxiosResponse<BaseResponseTaskRecommendationResponse>,
>(
  sessionId: number,
  recommendationId: number,
  taskRecommendationUpdate: TaskRecommendationUpdate,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.put(
    `/api/v1/sessions/${sessionId}/recommendations/${recommendationId}`,
    taskRecommendationUpdate,
    options
  );
};

/**
 * SPA 路由回退，所有非静态资源请求都返回 index.html
 * @summary Serve Spa
 */
export const serveSpaWebFullPathGet = <TData = AxiosResponse<unknown>>(
  fullPath: string,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/web/${fullPath}`, options);
};

/**
 * SPA 根路径
 * @summary Serve Spa Root
 */
export const serveSpaRootWebGet = <TData = AxiosResponse<unknown>>(options?: AxiosRequestConfig): Promise<TData> => {
  return axios.get('/web', options);
};

export type RootGetResult = AxiosResponse<unknown>;
export type HealthCheckHealthGetResult = AxiosResponse<unknown>;
export type LoginApiV1AuthLoginPostResult = AxiosResponse<BaseResponseToken>;
export type RefreshTokenApiV1AuthRefreshPostResult = AxiosResponse<BaseResponseToken>;
export type RegisterApiV1AuthRegisterPostResult = AxiosResponse<BaseResponseUserResponse>;
export type GetCurrentUserInfoApiV1AuthMeGetResult = AxiosResponse<BaseResponseUserResponse>;
export type UpdateCurrentUserApiV1AuthMePutResult = AxiosResponse<BaseResponseUserResponse>;
export type ChangePasswordApiV1AuthChangePasswordPostResult = AxiosResponse<BaseResponseNoneType>;
export type GetUsersApiV1UsersGetResult = AxiosResponse<BaseResponsePageResponseUserResponse>;
export type CreateUserApiV1UsersPostResult = AxiosResponse<BaseResponseUserResponse>;
export type GetUserApiV1UsersUserIdGetResult = AxiosResponse<BaseResponseUserResponse>;
export type UpdateUserApiV1UsersUserIdPutResult = AxiosResponse<BaseResponseUserResponse>;
export type DeleteUserApiV1UsersUserIdDeleteResult = AxiosResponse<BaseResponseNoneType>;
export type GetDataSourcesApiV1DataSourcesGetResult = AxiosResponse<BaseResponsePageResponseDataSourceResponse>;
export type CreateDataSourceApiV1DataSourcesPostResult = AxiosResponse<BaseResponseDataSourceResponse>;
export type GetDataSourceApiV1DataSourcesDataSourceIdGetResult = AxiosResponse<BaseResponseDataSourceResponse>;
export type UpdateDataSourceApiV1DataSourcesDataSourceIdPutResult = AxiosResponse<BaseResponseDataSourceResponse>;
export type DeleteDataSourceApiV1DataSourcesDataSourceIdDeleteResult = AxiosResponse<BaseResponseNoneType>;
export type TestDataSourceConnectionApiV1DataSourcesDataSourceIdTestPostResult =
  AxiosResponse<BaseResponseDataSourceTestResult>;
export type SyncDataSourceSchemaApiV1DataSourcesDataSourceIdSyncSchemaPostResult =
  AxiosResponse<BaseResponseDataSourceSchemaResponse>;
export type GetDataSourceSchemaApiV1DataSourcesDataSourceIdSchemaGetResult =
  AxiosResponse<BaseResponseDataSourceSchemaResponse>;
export type GetFilesApiV1FilesGetResult = AxiosResponse<BaseResponsePageResponseUploadedFileResponse>;
export type GetFileApiV1FilesFileIdGetResult = AxiosResponse<BaseResponseUploadedFileResponse>;
export type DeleteFileApiV1FilesFileIdDeleteResult = AxiosResponse<BaseResponseNoneType>;
export type UploadFileApiV1FilesUploadPostResult = AxiosResponse<BaseResponseUploadedFileResponse>;
export type GetFilePreviewApiV1FilesFileIdPreviewGetResult = AxiosResponse<BaseResponseFilePreviewResponse>;
export type GetDownloadUrlApiV1FilesFileIdDownloadUrlGetResult = AxiosResponse<BaseResponseStr>;
export type GetSessionsApiV1SessionsGetResult = AxiosResponse<BaseResponsePageResponseAnalysisSessionResponse>;
export type CreateSessionApiV1SessionsPostResult = AxiosResponse<BaseResponseAnalysisSessionResponse>;
export type GetSessionApiV1SessionsSessionIdGetResult = AxiosResponse<BaseResponseAnalysisSessionDetail>;
export type UpdateSessionApiV1SessionsSessionIdPutResult = AxiosResponse<BaseResponseAnalysisSessionResponse>;
export type DeleteSessionApiV1SessionsSessionIdDeleteResult = AxiosResponse<BaseResponseNoneType>;
export type ArchiveSessionApiV1SessionsSessionIdArchivePostResult = AxiosResponse<BaseResponseAnalysisSessionResponse>;
export type UploadSessionFileApiV1SessionsSessionIdFilesUploadPostResult = AxiosResponse<BaseResponseDictStrAny>;
export type ListSessionFilesApiV1SessionsSessionIdFilesGetResult = AxiosResponse<BaseResponseDictStrAny>;
export type DownloadSessionFileApiV1SessionsSessionIdFilesFilenameGetResult = AxiosResponse<unknown>;
export type ChatApiV1SessionsSessionIdChatPostResult = AxiosResponse<void>;
export type GetMessagesApiV1SessionsSessionIdMessagesGetResult =
  AxiosResponse<BaseResponsePageResponseChatMessageResponse>;
export type ClearMessagesApiV1SessionsSessionIdMessagesDeleteResult = AxiosResponse<BaseResponseInt>;
export type GetRecommendationsApiV1SessionsSessionIdRecommendationsGetResult =
  AxiosResponse<BaseResponsePageResponseTaskRecommendationResponse>;
export type GenerateRecommendationsApiV1SessionsSessionIdRecommendationsPostResult =
  AxiosResponse<BaseResponseListTaskRecommendationResponse>;
export type DismissAllRecommendationsApiV1SessionsSessionIdRecommendationsDeleteResult =
  AxiosResponse<BaseResponseNoneType>;
export type GenerateFollowupRecommendationsApiV1SessionsSessionIdRecommendationsFollowupPostResult =
  AxiosResponse<BaseResponseListTaskRecommendationResponse>;
export type UpdateRecommendationApiV1SessionsSessionIdRecommendationsRecommendationIdPutResult =
  AxiosResponse<BaseResponseTaskRecommendationResponse>;
export type ServeSpaWebFullPathGetResult = AxiosResponse<unknown>;
export type ServeSpaRootWebGetResult = AxiosResponse<unknown>;
