/**
 * Generated by orval v8.0.0-rc.2 🍺
 * Do not edit manually.
 * Fast Data Agent
 * 基于 LangGraph 的 AI 数据分析平台
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

/**
 * 会话描述
 */
export type AnalysisSessionCreateDescription = string | null;

/**
 * 关联的数据源ID（可选）
 */
export type AnalysisSessionCreateDataSourceId = string | null;

export type AnalysisSessionCreateConfigAnyOf = { [key: string]: unknown };

/**
 * 会话配置
 */
export type AnalysisSessionCreateConfig = AnalysisSessionCreateConfigAnyOf | null;

/**
 * 创建分析会话请求
 */
export interface AnalysisSessionCreate {
  /**
   * 会话名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 会话描述 */
  description?: AnalysisSessionCreateDescription;
  /** 关联的数据源ID（可选） */
  data_source_id?: AnalysisSessionCreateDataSourceId;
  /** 会话配置 */
  config?: AnalysisSessionCreateConfig;
}

/**
 * 会话描述
 */
export type AnalysisSessionDetailDescription = string | null;

/**
 * 关联的数据源ID
 */
export type AnalysisSessionDetailDataSourceId = string | null;

export type AnalysisSessionDetailConfigAnyOf = { [key: string]: unknown };

/**
 * 会话配置
 */
export type AnalysisSessionDetailConfig = AnalysisSessionDetailConfigAnyOf | null;

/**
 * 创建时间
 */
export type AnalysisSessionDetailCreateTime = string | null;

/**
 * 更新时间
 */
export type AnalysisSessionDetailUpdateTime = string | null;

/**
 * 关联的数据源详情
 */
export type AnalysisSessionDetailDataSource = DataSourceResponse | null;

/**
 * 分析会话详情（包含完整数据源信息）
 */
export interface AnalysisSessionDetail {
  /**
   * 会话名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 会话描述 */
  description?: AnalysisSessionDetailDescription;
  /** 会话ID */
  id: string;
  /** 所属用户ID */
  user_id: string;
  /** 关联的数据源ID */
  data_source_id?: AnalysisSessionDetailDataSourceId;
  /** 会话配置 */
  config?: AnalysisSessionDetailConfig;
  /** 会话状态 */
  status: string;
  /** 消息数量 */
  message_count?: number;
  /** 创建时间 */
  create_time?: AnalysisSessionDetailCreateTime;
  /** 更新时间 */
  update_time?: AnalysisSessionDetailUpdateTime;
  /** 关联的数据源详情 */
  data_source?: AnalysisSessionDetailDataSource;
}

/**
 * 会话描述
 */
export type AnalysisSessionResponseDescription = string | null;

/**
 * 关联的数据源ID
 */
export type AnalysisSessionResponseDataSourceId = string | null;

export type AnalysisSessionResponseConfigAnyOf = { [key: string]: unknown };

/**
 * 会话配置
 */
export type AnalysisSessionResponseConfig = AnalysisSessionResponseConfigAnyOf | null;

/**
 * 创建时间
 */
export type AnalysisSessionResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type AnalysisSessionResponseUpdateTime = string | null;

/**
 * 分析会话响应
 */
export interface AnalysisSessionResponse {
  /**
   * 会话名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 会话描述 */
  description?: AnalysisSessionResponseDescription;
  /** 会话ID */
  id: string;
  /** 所属用户ID */
  user_id: string;
  /** 关联的数据源ID */
  data_source_id?: AnalysisSessionResponseDataSourceId;
  /** 会话配置 */
  config?: AnalysisSessionResponseConfig;
  /** 会话状态 */
  status: string;
  /** 消息数量 */
  message_count?: number;
  /** 创建时间 */
  create_time?: AnalysisSessionResponseCreateTime;
  /** 更新时间 */
  update_time?: AnalysisSessionResponseUpdateTime;
}

/**
 * 会话名称
 */
export type AnalysisSessionUpdateName = string | null;

/**
 * 会话描述
 */
export type AnalysisSessionUpdateDescription = string | null;

/**
 * 关联的数据源ID（可选）
 */
export type AnalysisSessionUpdateDataSourceId = string | null;

export type AnalysisSessionUpdateConfigAnyOf = { [key: string]: unknown };

/**
 * 会话配置
 */
export type AnalysisSessionUpdateConfig = AnalysisSessionUpdateConfigAnyOf | null;

/**
 * 更新分析会话请求
 */
export interface AnalysisSessionUpdate {
  /** 会话名称 */
  name?: AnalysisSessionUpdateName;
  /** 会话描述 */
  description?: AnalysisSessionUpdateDescription;
  /** 关联的数据源ID（可选） */
  data_source_id?: AnalysisSessionUpdateDataSourceId;
  /** 会话配置 */
  config?: AnalysisSessionUpdateConfig;
}

/**
 * 错误信息（如果有）
 */
export type AutoCreatedRawDataErrorMessage = string | null;

/**
 * 自动创建的 RawData 简要信息
 */
export interface AutoCreatedRawData {
  /** 数据对象ID */
  raw_data_id: string;
  /** 数据对象名称 */
  name: string;
  /** 来源表名 */
  table_name: string;
  /** 状态: created/ready/error */
  status: string;
  /** 错误信息（如果有） */
  error_message?: AutoCreatedRawDataErrorMessage;
}

export type BaseResponseAnalysisSessionDetailData = AnalysisSessionDetail | null;

export type BaseResponseAnalysisSessionDetailErr = AnalysisSessionDetail | null;

export interface BaseResponseAnalysisSessionDetail {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseAnalysisSessionDetailData;
  err?: BaseResponseAnalysisSessionDetailErr;
}

export type BaseResponseAnalysisSessionResponseData = AnalysisSessionResponse | null;

export type BaseResponseAnalysisSessionResponseErr = AnalysisSessionResponse | null;

export interface BaseResponseAnalysisSessionResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseAnalysisSessionResponseData;
  err?: BaseResponseAnalysisSessionResponseErr;
}

export type BaseResponseBatchCreateFromConnectionResponseData = BatchCreateFromConnectionResponse | null;

export type BaseResponseBatchCreateFromConnectionResponseErr = BatchCreateFromConnectionResponse | null;

export interface BaseResponseBatchCreateFromConnectionResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseBatchCreateFromConnectionResponseData;
  err?: BaseResponseBatchCreateFromConnectionResponseErr;
}

export type BaseResponseDataSourcePreviewResponseData = DataSourcePreviewResponse | null;

export type BaseResponseDataSourcePreviewResponseErr = DataSourcePreviewResponse | null;

export interface BaseResponseDataSourcePreviewResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDataSourcePreviewResponseData;
  err?: BaseResponseDataSourcePreviewResponseErr;
}

export type BaseResponseDataSourceResponseData = DataSourceResponse | null;

export type BaseResponseDataSourceResponseErr = DataSourceResponse | null;

export interface BaseResponseDataSourceResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDataSourceResponseData;
  err?: BaseResponseDataSourceResponseErr;
}

export type BaseResponseDatabaseConnectionResponseData = DatabaseConnectionResponse | null;

export type BaseResponseDatabaseConnectionResponseErr = DatabaseConnectionResponse | null;

export interface BaseResponseDatabaseConnectionResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDatabaseConnectionResponseData;
  err?: BaseResponseDatabaseConnectionResponseErr;
}

export type BaseResponseDatabaseConnectionTablesResponseData = DatabaseConnectionTablesResponse | null;

export type BaseResponseDatabaseConnectionTablesResponseErr = DatabaseConnectionTablesResponse | null;

export interface BaseResponseDatabaseConnectionTablesResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDatabaseConnectionTablesResponseData;
  err?: BaseResponseDatabaseConnectionTablesResponseErr;
}

export type BaseResponseDatabaseConnectionTestResultData = DatabaseConnectionTestResult | null;

export type BaseResponseDatabaseConnectionTestResultErr = DatabaseConnectionTestResult | null;

export interface BaseResponseDatabaseConnectionTestResult {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDatabaseConnectionTestResultData;
  err?: BaseResponseDatabaseConnectionTestResultErr;
}

export type BaseResponseDatabaseConnectionWithRawResponseData = DatabaseConnectionWithRawResponse | null;

export type BaseResponseDatabaseConnectionWithRawResponseErr = DatabaseConnectionWithRawResponse | null;

export interface BaseResponseDatabaseConnectionWithRawResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDatabaseConnectionWithRawResponseData;
  err?: BaseResponseDatabaseConnectionWithRawResponseErr;
}

export type BaseResponseDatabaseTableSchemaResponseData = DatabaseTableSchemaResponse | null;

export type BaseResponseDatabaseTableSchemaResponseErr = DatabaseTableSchemaResponse | null;

export interface BaseResponseDatabaseTableSchemaResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDatabaseTableSchemaResponseData;
  err?: BaseResponseDatabaseTableSchemaResponseErr;
}

export type BaseResponseFilePreviewResponseData = FilePreviewResponse | null;

export type BaseResponseFilePreviewResponseErr = FilePreviewResponse | null;

export interface BaseResponseFilePreviewResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseFilePreviewResponseData;
  err?: BaseResponseFilePreviewResponseErr;
}

export interface BaseResponseNoneType {
  success: boolean;
  code: number;
  msg: string;
  data?: null;
  err?: null;
}

export type BaseResponsePageResponseAnalysisSessionResponseData = PageResponseAnalysisSessionResponse | null;

export type BaseResponsePageResponseAnalysisSessionResponseErr = PageResponseAnalysisSessionResponse | null;

export interface BaseResponsePageResponseAnalysisSessionResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseAnalysisSessionResponseData;
  err?: BaseResponsePageResponseAnalysisSessionResponseErr;
}

export type BaseResponsePageResponseChatMessageResponseData = PageResponseChatMessageResponse | null;

export type BaseResponsePageResponseChatMessageResponseErr = PageResponseChatMessageResponse | null;

export interface BaseResponsePageResponseChatMessageResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseChatMessageResponseData;
  err?: BaseResponsePageResponseChatMessageResponseErr;
}

export type BaseResponsePageResponseDataSourceResponseData = PageResponseDataSourceResponse | null;

export type BaseResponsePageResponseDataSourceResponseErr = PageResponseDataSourceResponse | null;

export interface BaseResponsePageResponseDataSourceResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseDataSourceResponseData;
  err?: BaseResponsePageResponseDataSourceResponseErr;
}

export type BaseResponsePageResponseDatabaseConnectionResponseData = PageResponseDatabaseConnectionResponse | null;

export type BaseResponsePageResponseDatabaseConnectionResponseErr = PageResponseDatabaseConnectionResponse | null;

export interface BaseResponsePageResponseDatabaseConnectionResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseDatabaseConnectionResponseData;
  err?: BaseResponsePageResponseDatabaseConnectionResponseErr;
}

export type BaseResponsePageResponseRawDataResponseData = PageResponseRawDataResponse | null;

export type BaseResponsePageResponseRawDataResponseErr = PageResponseRawDataResponse | null;

export interface BaseResponsePageResponseRawDataResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseRawDataResponseData;
  err?: BaseResponsePageResponseRawDataResponseErr;
}

export type BaseResponsePageResponseTaskRecommendationResponseData = PageResponseTaskRecommendationResponse | null;

export type BaseResponsePageResponseTaskRecommendationResponseErr = PageResponseTaskRecommendationResponse | null;

export interface BaseResponsePageResponseTaskRecommendationResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseTaskRecommendationResponseData;
  err?: BaseResponsePageResponseTaskRecommendationResponseErr;
}

export type BaseResponsePageResponseUploadedFileResponseData = PageResponseUploadedFileResponse | null;

export type BaseResponsePageResponseUploadedFileResponseErr = PageResponseUploadedFileResponse | null;

export interface BaseResponsePageResponseUploadedFileResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseUploadedFileResponseData;
  err?: BaseResponsePageResponseUploadedFileResponseErr;
}

export type BaseResponsePageResponseUserResponseData = PageResponseUserResponse | null;

export type BaseResponsePageResponseUserResponseErr = PageResponseUserResponse | null;

export interface BaseResponsePageResponseUserResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponsePageResponseUserResponseData;
  err?: BaseResponsePageResponseUserResponseErr;
}

export type BaseResponseRawDataPreviewResponseData = RawDataPreviewResponse | null;

export type BaseResponseRawDataPreviewResponseErr = RawDataPreviewResponse | null;

export interface BaseResponseRawDataPreviewResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseRawDataPreviewResponseData;
  err?: BaseResponseRawDataPreviewResponseErr;
}

export type BaseResponseRawDataResponseData = RawDataResponse | null;

export type BaseResponseRawDataResponseErr = RawDataResponse | null;

export interface BaseResponseRawDataResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseRawDataResponseData;
  err?: BaseResponseRawDataResponseErr;
}

export type BaseResponseSuggestMappingsResponseData = SuggestMappingsResponse | null;

export type BaseResponseSuggestMappingsResponseErr = SuggestMappingsResponse | null;

export interface BaseResponseSuggestMappingsResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseSuggestMappingsResponseData;
  err?: BaseResponseSuggestMappingsResponseErr;
}

export type BaseResponseSuggestTargetFieldsResponseData = SuggestTargetFieldsResponse | null;

export type BaseResponseSuggestTargetFieldsResponseErr = SuggestTargetFieldsResponse | null;

export interface BaseResponseSuggestTargetFieldsResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseSuggestTargetFieldsResponseData;
  err?: BaseResponseSuggestTargetFieldsResponseErr;
}

export type BaseResponseTaskRecommendationResponseData = TaskRecommendationResponse | null;

export type BaseResponseTaskRecommendationResponseErr = TaskRecommendationResponse | null;

export interface BaseResponseTaskRecommendationResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseTaskRecommendationResponseData;
  err?: BaseResponseTaskRecommendationResponseErr;
}

export type BaseResponseTokenData = Token | null;

export type BaseResponseTokenErr = Token | null;

export interface BaseResponseToken {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseTokenData;
  err?: BaseResponseTokenErr;
}

export type BaseResponseUploadedFileResponseData = UploadedFileResponse | null;

export type BaseResponseUploadedFileResponseErr = UploadedFileResponse | null;

export interface BaseResponseUploadedFileResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseUploadedFileResponseData;
  err?: BaseResponseUploadedFileResponseErr;
}

export type BaseResponseUploadedFileWithRawDataResponseData = UploadedFileWithRawDataResponse | null;

export type BaseResponseUploadedFileWithRawDataResponseErr = UploadedFileWithRawDataResponse | null;

export interface BaseResponseUploadedFileWithRawDataResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseUploadedFileWithRawDataResponseData;
  err?: BaseResponseUploadedFileWithRawDataResponseErr;
}

export type BaseResponseUserResponseData = UserResponse | null;

export type BaseResponseUserResponseErr = UserResponse | null;

export interface BaseResponseUserResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseUserResponseData;
  err?: BaseResponseUserResponseErr;
}

export type BaseResponseDictStrAnyDataAnyOf = { [key: string]: unknown };

export type BaseResponseDictStrAnyData = BaseResponseDictStrAnyDataAnyOf | null;

export type BaseResponseDictStrAnyErrAnyOf = { [key: string]: unknown };

export type BaseResponseDictStrAnyErr = BaseResponseDictStrAnyErrAnyOf | null;

export interface BaseResponseDictStrAny {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseDictStrAnyData;
  err?: BaseResponseDictStrAnyErr;
}

export type BaseResponseIntData = number | null;

export type BaseResponseIntErr = number | null;

export interface BaseResponseInt {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseIntData;
  err?: BaseResponseIntErr;
}

export type BaseResponseListTaskRecommendationResponseData = TaskRecommendationResponse[] | null;

export type BaseResponseListTaskRecommendationResponseErr = TaskRecommendationResponse[] | null;

export interface BaseResponseListTaskRecommendationResponse {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseListTaskRecommendationResponseData;
  err?: BaseResponseListTaskRecommendationResponseErr;
}

export type BaseResponseStrData = string | null;

export type BaseResponseStrErr = string | null;

export interface BaseResponseStr {
  success: boolean;
  code: number;
  msg: string;
  data?: BaseResponseStrData;
  err?: BaseResponseStrErr;
}

/**
 * 名称前缀（可选）
 */
export type BatchCreateFromConnectionRequestNamePrefix = string | null;

/**
 * 从数据库连接批量创建数据对象请求
 */
export interface BatchCreateFromConnectionRequest {
  /** 数据库连接ID */
  connection_id: string;
  /**
   * 要创建的表列表
   * @minItems 1
   */
  tables: TableSelection[];
  /** 是否自动同步列信息 */
  auto_sync?: boolean;
  /** 名称前缀（可选） */
  name_prefix?: BatchCreateFromConnectionRequestNamePrefix;
}

/**
 * 从数据库连接批量创建数据对象响应
 */
export interface BatchCreateFromConnectionResponse {
  /** 成功创建的数量 */
  success_count: number;
  /** 失败的数量 */
  failed_count: number;
  /** 每个表的创建结果 */
  results?: BatchCreateResult[];
}

/**
 * 错误信息（如果有）
 */
export type BatchCreateResultErrorMessage = string | null;

/**
 * 批量创建结果
 */
export interface BatchCreateResult {
  /** 创建的数据对象ID */
  raw_data_id: string;
  /** 数据对象名称 */
  name: string;
  /** 表名 */
  table_name: string;
  /** 状态: created/syncing/ready/error */
  status: string;
  /** 错误信息（如果有） */
  error_message?: BatchCreateResultErrorMessage;
}

export interface BodyUploadFileApiV1FilesUploadPost {
  /** 要上传的文件 */
  file: Blob;
}

export interface BodyUploadSessionFileApiV1SessionsSessionIdFilesUploadPost {
  file: Blob;
}

/**
 * 创建对话消息请求（用户发送）
 */
export interface ChatMessageCreate {
  /**
   * 消息内容
   * @minLength 1
   */
  content: string;
}

/**
 * LangChain 消息ID
 */
export type ChatMessageResponseMessageId = string | null;

/**
 * 消息名称
 */
export type ChatMessageResponseName = string | null;

export type ChatMessageResponseToolCallsAnyOfItem = { [key: string]: unknown };

/**
 * 工具调用列表
 */
export type ChatMessageResponseToolCalls = ChatMessageResponseToolCallsAnyOfItem[] | null;

export type ChatMessageResponseUsageMetadataAnyOf = { [key: string]: unknown };

/**
 * Token使用统计
 */
export type ChatMessageResponseUsageMetadata = ChatMessageResponseUsageMetadataAnyOf | null;

/**
 * 工具调用ID
 */
export type ChatMessageResponseToolCallId = string | null;

export type ChatMessageResponseArtifactAnyOf = { [key: string]: unknown };

/**
 * 工具产出物(图表、表格等)
 */
export type ChatMessageResponseArtifact = ChatMessageResponseArtifactAnyOf | null;

/**
 * 创建时间
 */
export type ChatMessageResponseCreateTime = string | null;

/**
 * 对话消息响应 - 与 LangChain 消息格式对齐
 */
export interface ChatMessageResponse {
  /** 消息ID */
  id: string;
  /** 所属会话ID */
  session_id: string;
  /** 消息序号(会话内递增，用于排序) */
  seq: number;
  /** 消息类型: human/ai/system/tool */
  message_type: string;
  /** 消息内容 */
  content: string;
  /** LangChain 消息ID */
  message_id?: ChatMessageResponseMessageId;
  /** 消息名称 */
  name?: ChatMessageResponseName;
  /** 工具调用列表 */
  tool_calls?: ChatMessageResponseToolCalls;
  /** Token使用统计 */
  usage_metadata?: ChatMessageResponseUsageMetadata;
  /** 工具调用ID */
  tool_call_id?: ChatMessageResponseToolCallId;
  /** 工具产出物(图表、表格等) */
  artifact?: ChatMessageResponseArtifact;
  /** 创建时间 */
  create_time?: ChatMessageResponseCreateTime;
}

/**
 * 用户修正的类型
 */
export type ColumnSchemaUserTypeOverride = string | null;

/**
 * 列注释
 */
export type ColumnSchemaComment = string | null;

/**
 * 列结构
 */
export interface ColumnSchema {
  /** 列名 */
  name: string;
  /** 数据类型 */
  data_type: string;
  /** 是否可空 */
  nullable?: boolean;
  /** 用户修正的类型 */
  user_type_override?: ColumnSchemaUserTypeOverride;
  /** 列注释 */
  comment?: ColumnSchemaComment;
}

/**
 * 数据源分类
 */
export type DataSourceCategory = typeof DataSourceCategory[keyof typeof DataSourceCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataSourceCategory = {
  fact: 'fact',
  dimension: 'dimension',
  event: 'event',
  other: 'other',
} as const;

/**
 * 数据源描述
 */
export type DataSourceCreateDescription = string | null;

/**
 * 数据源分类
 */
export type DataSourceCreateCategory = DataSourceCategory | null;

/**
 * 创建数据源请求
 */
export interface DataSourceCreate {
  /**
   * 数据源名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 数据源描述 */
  description?: DataSourceCreateDescription;
  /** 数据源分类 */
  category?: DataSourceCreateCategory;
  /** 目标字段定义 */
  target_fields?: TargetField[];
  /** 数据对象字段映射 */
  raw_mappings?: FieldMapping[];
}

/**
 * 数据源预览请求（合并后的数据）
 */
export interface DataSourcePreviewRequest {
  /**
   * 预览行数
   * @minimum 1
   * @maximum 1000
   */
  limit?: number;
}

export type DataSourcePreviewResponseRowsItem = { [key: string]: unknown };

/**
 * 各 Raw 源的行数统计
 */
export type DataSourcePreviewResponseSourceStats = {[key: string]: number};

/**
 * 数据源预览响应
 */
export interface DataSourcePreviewResponse {
  /** 字段定义 */
  columns?: TargetField[];
  /** 合并后的数据行 */
  rows?: DataSourcePreviewResponseRowsItem[];
  /** 各 Raw 源的行数统计 */
  source_stats?: DataSourcePreviewResponseSourceStats;
  /** 预览时间 */
  preview_at: string;
}

/**
 * 数据源描述
 */
export type DataSourceResponseDescription = string | null;

/**
 * 数据源分类
 */
export type DataSourceResponseCategory = DataSourceCategory | null;

/**
 * 目标字段定义
 */
export type DataSourceResponseTargetFields = TargetField[] | null;

export type DataSourceResponseSchemaCacheAnyOf = { [key: string]: unknown };

/**
 * 表结构缓存
 */
export type DataSourceResponseSchemaCache = DataSourceResponseSchemaCacheAnyOf | null;

/**
 * 数据对象映射
 */
export type DataSourceResponseRawMappings = RawMappingResponse[] | null;

/**
 * 创建时间
 */
export type DataSourceResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type DataSourceResponseUpdateTime = string | null;

/**
 * 数据源响应
 */
export interface DataSourceResponse {
  /**
   * 数据源名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 数据源描述 */
  description?: DataSourceResponseDescription;
  /** 数据源分类 */
  category?: DataSourceResponseCategory;
  /** 数据源ID */
  id: string;
  /** 所属用户ID */
  user_id: string;
  /** 目标字段定义 */
  target_fields?: DataSourceResponseTargetFields;
  /** 表结构缓存 */
  schema_cache?: DataSourceResponseSchemaCache;
  /** 数据对象映射 */
  raw_mappings?: DataSourceResponseRawMappings;
  /** 创建时间 */
  create_time?: DataSourceResponseCreateTime;
  /** 更新时间 */
  update_time?: DataSourceResponseUpdateTime;
}

/**
 * 数据源名称
 */
export type DataSourceUpdateName = string | null;

/**
 * 数据源描述
 */
export type DataSourceUpdateDescription = string | null;

/**
 * 数据源分类
 */
export type DataSourceUpdateCategory = DataSourceCategory | null;

/**
 * 目标字段定义
 */
export type DataSourceUpdateTargetFields = TargetField[] | null;

/**
 * 数据对象字段映射
 */
export type DataSourceUpdateRawMappings = FieldMapping[] | null;

/**
 * 更新数据源请求
 */
export interface DataSourceUpdate {
  /** 数据源名称 */
  name?: DataSourceUpdateName;
  /** 数据源描述 */
  description?: DataSourceUpdateDescription;
  /** 数据源分类 */
  category?: DataSourceUpdateCategory;
  /** 目标字段定义 */
  target_fields?: DataSourceUpdateTargetFields;
  /** 数据对象字段映射 */
  raw_mappings?: DataSourceUpdateRawMappings;
}

export type DatabaseConnectionConfigExtraParamsAnyOf = { [key: string]: unknown };

/**
 * 额外连接参数
 */
export type DatabaseConnectionConfigExtraParams = DatabaseConnectionConfigExtraParamsAnyOf | null;

/**
 * 数据库连接配置
 */
export interface DatabaseConnectionConfig {
  db_type: DatabaseType;
  /**
   * 数据库主机
   * @minLength 1
   * @maxLength 255
   */
  host: string;
  /**
   * 数据库端口
   * @minimum 1
   * @maximum 65535
   */
  port: number;
  /**
   * 数据库名
   * @minLength 1
   * @maxLength 100
   */
  database: string;
  /**
   * 用户名
   * @minLength 1
   * @maxLength 100
   */
  username: string;
  /**
   * 密码
   * @minLength 1
   * @maxLength 255
   */
  password: string;
  /** 额外连接参数 */
  extra_params?: DatabaseConnectionConfigExtraParams;
}

/**
 * 连接描述
 */
export type DatabaseConnectionCreateDescription = string | null;

/**
 * 创建数据库连接请求
 */
export interface DatabaseConnectionCreate {
  /**
   * 连接名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 连接描述 */
  description?: DatabaseConnectionCreateDescription;
  /** 连接配置 */
  config: DatabaseConnectionConfig;
}

/**
 * 连接描述
 */
export type DatabaseConnectionResponseDescription = string | null;

export type DatabaseConnectionResponseExtraParamsAnyOf = { [key: string]: unknown };

/**
 * 额外连接参数
 */
export type DatabaseConnectionResponseExtraParams = DatabaseConnectionResponseExtraParamsAnyOf | null;

/**
 * 最后测试时间
 */
export type DatabaseConnectionResponseLastTestedAt = string | null;

/**
 * 创建时间
 */
export type DatabaseConnectionResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type DatabaseConnectionResponseUpdateTime = string | null;

/**
 * 数据库连接响应（不返回密码）
 */
export interface DatabaseConnectionResponse {
  /**
   * 连接名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 连接描述 */
  description?: DatabaseConnectionResponseDescription;
  /** 连接ID */
  id: string;
  /** 所属用户ID */
  user_id: string;
  db_type: DatabaseType;
  /** 数据库主机 */
  host: string;
  /** 数据库端口 */
  port: number;
  /** 数据库名 */
  database: string;
  /** 用户名 */
  username: string;
  /** 额外连接参数 */
  extra_params?: DatabaseConnectionResponseExtraParams;
  /** 最后测试时间 */
  last_tested_at?: DatabaseConnectionResponseLastTestedAt;
  /** 是否可用 */
  is_active?: boolean;
  /** 创建时间 */
  create_time?: DatabaseConnectionResponseCreateTime;
  /** 更新时间 */
  update_time?: DatabaseConnectionResponseUpdateTime;
}

/**
 * 数据库连接的表列表响应
 */
export interface DatabaseConnectionTablesResponse {
  /** 连接ID */
  connection_id: string;
  /** 表列表 */
  tables?: DatabaseTableInfo[];
}

/**
 * 连接延迟（毫秒）
 */
export type DatabaseConnectionTestResultLatencyMs = number | null;

/**
 * 数据库连接测试结果
 */
export interface DatabaseConnectionTestResult {
  /** 是否连接成功 */
  success: boolean;
  /** 测试结果消息 */
  message: string;
  /** 连接延迟（毫秒） */
  latency_ms?: DatabaseConnectionTestResultLatencyMs;
}

/**
 * 连接名称
 */
export type DatabaseConnectionUpdateName = string | null;

/**
 * 连接描述
 */
export type DatabaseConnectionUpdateDescription = string | null;

/**
 * 连接配置
 */
export type DatabaseConnectionUpdateConfig = DatabaseConnectionConfig | null;

/**
 * 更新数据库连接请求
 */
export interface DatabaseConnectionUpdate {
  /** 连接名称 */
  name?: DatabaseConnectionUpdateName;
  /** 连接描述 */
  description?: DatabaseConnectionUpdateDescription;
  /** 连接配置 */
  config?: DatabaseConnectionUpdateConfig;
}

/**
 * 连接描述
 */
export type DatabaseConnectionWithRawResponseDescription = string | null;

export type DatabaseConnectionWithRawResponseExtraParamsAnyOf = { [key: string]: unknown };

/**
 * 额外连接参数
 */
export type DatabaseConnectionWithRawResponseExtraParams = DatabaseConnectionWithRawResponseExtraParamsAnyOf | null;

/**
 * 最后测试时间
 */
export type DatabaseConnectionWithRawResponseLastTestedAt = string | null;

/**
 * 创建时间
 */
export type DatabaseConnectionWithRawResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type DatabaseConnectionWithRawResponseUpdateTime = string | null;

/**
 * 自动创建 RawData 的结果列表
 */
export type DatabaseConnectionWithRawResponseAutoRawResults = AutoCreatedRawData[] | null;

/**
 * 自动创建 RawData 的错误信息
 */
export type DatabaseConnectionWithRawResponseAutoRawError = string | null;

/**
 * 数据库连接响应（包含自动创建的 RawData 结果）
 */
export interface DatabaseConnectionWithRawResponse {
  /**
   * 连接名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 连接描述 */
  description?: DatabaseConnectionWithRawResponseDescription;
  /** 连接ID */
  id: string;
  /** 所属用户ID */
  user_id: string;
  db_type: DatabaseType;
  /** 数据库主机 */
  host: string;
  /** 数据库端口 */
  port: number;
  /** 数据库名 */
  database: string;
  /** 用户名 */
  username: string;
  /** 额外连接参数 */
  extra_params?: DatabaseConnectionWithRawResponseExtraParams;
  /** 最后测试时间 */
  last_tested_at?: DatabaseConnectionWithRawResponseLastTestedAt;
  /** 是否可用 */
  is_active?: boolean;
  /** 创建时间 */
  create_time?: DatabaseConnectionWithRawResponseCreateTime;
  /** 更新时间 */
  update_time?: DatabaseConnectionWithRawResponseUpdateTime;
  /** 自动创建 RawData 的结果列表 */
  auto_raw_results?: DatabaseConnectionWithRawResponseAutoRawResults;
  /** 自动创建 RawData 的错误信息 */
  auto_raw_error?: DatabaseConnectionWithRawResponseAutoRawError;
}

/**
 * 表注释
 */
export type DatabaseTableInfoComment = string | null;

/**
 * 数据库表信息
 */
export interface DatabaseTableInfo {
  /** Schema名称 */
  schema_name: string;
  /** 表名 */
  table_name: string;
  /** 表类型: TABLE/VIEW */
  table_type?: string;
  /** 表注释 */
  comment?: DatabaseTableInfoComment;
}

/**
 * Schema 名称
 */
export type DatabaseTableSchemaResponseSchemaName = string | null;

/**
 * 行数估算
 */
export type DatabaseTableSchemaResponseRowCount = number | null;

/**
 * 数据库表结构响应
 */
export interface DatabaseTableSchemaResponse {
  /** 连接ID */
  connection_id: string;
  /** Schema 名称 */
  schema_name?: DatabaseTableSchemaResponseSchemaName;
  /** 表名 */
  table_name: string;
  /** 列信息 */
  columns?: TableColumnInfo[];
  /** 行数估算 */
  row_count?: DatabaseTableSchemaResponseRowCount;
}

/**
 * 数据库类型
 */
export type DatabaseType = typeof DatabaseType[keyof typeof DatabaseType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DatabaseType = {
  mysql: 'mysql',
  postgresql: 'postgresql',
} as const;

/**
 * 字段映射: {target_field: source_field_or_null}
 */
export type FieldMappingMappings = {[key: string]: string | null};

/**
 * 单个 Raw 的字段映射
 */
export interface FieldMapping {
  /** 数据对象ID */
  raw_data_id: string;
  /** 字段映射: {target_field: source_field_or_null} */
  mappings: FieldMappingMappings;
  /** 优先级（数值越大优先级越高） */
  priority?: number;
  /** 是否启用 */
  is_enabled?: boolean;
}

/**
 * 单个字段映射建议
 */
export interface FieldMappingSuggestionResponse {
  /** 目标字段名 */
  target_field: string;
  /** 推荐的源字段名 */
  source_field: string;
  /** 来源 RawData ID */
  raw_data_id: string;
  /** 来源 RawData 名称 */
  raw_data_name: string;
  /**
   * 匹配置信度 (0-1)
   * @minimum 0
   * @maximum 1
   */
  confidence: number;
  /** 推荐理由 */
  reason: string;
}

export type FilePreviewResponseColumnsItem = { [key: string]: unknown };

export type FilePreviewResponseDataItem = { [key: string]: unknown };

/**
 * 文件预览响应
 */
export interface FilePreviewResponse {
  /** 列信息 */
  columns: FilePreviewResponseColumnsItem[];
  /** 预览数据 */
  data: FilePreviewResponseDataItem[];
  /** 总行数 */
  total_rows: number;
}

/**
 * 文件类型
 */
export type FileType = typeof FileType[keyof typeof FileType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FileType = {
  csv: 'csv',
  excel: 'excel',
  json: 'json',
  parquet: 'parquet',
} as const;

export type GenerateFollowupRequestLastResultAnyOf = { [key: string]: unknown };

/**
 * 上次分析结果
 */
export type GenerateFollowupRequestLastResult = GenerateFollowupRequestLastResultAnyOf | null;

/**
 * 触发消息ID
 */
export type GenerateFollowupRequestTriggerMessageId = string | null;

/**
 * 生成追问推荐请求
 */
export interface GenerateFollowupRequest {
  /** 对话上下文 */
  conversation_context: string;
  /** 上次分析结果 */
  last_result?: GenerateFollowupRequestLastResult;
  /**
   * 最大推荐数量
   * @minimum 1
   * @maximum 5
   */
  max_count?: number;
  /** 触发消息ID */
  trigger_message_id?: GenerateFollowupRequestTriggerMessageId;
}

/**
 * 生成推荐请求
 */
export interface GenerateRecommendationsRequest {
  /**
   * 最大推荐数量
   * @minimum 1
   * @maximum 10
   */
  max_count?: number;
  /** 是否强制重新生成（会清理现有pending推荐） */
  force_regenerate?: boolean;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

/**
 * 登录请求
 */
export interface LoginRequest {
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /**
   * 密码
   * @minLength 6
   * @maxLength 128
   */
  password: string;
}

export interface PageResponseAnalysisSessionResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: AnalysisSessionResponse[];
}

export interface PageResponseChatMessageResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: ChatMessageResponse[];
}

export interface PageResponseDataSourceResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: DataSourceResponse[];
}

export interface PageResponseDatabaseConnectionResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: DatabaseConnectionResponse[];
}

export interface PageResponseRawDataResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: RawDataResponse[];
}

export interface PageResponseTaskRecommendationResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: TaskRecommendationResponse[];
}

export interface PageResponseUploadedFileResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: UploadedFileResponse[];
}

export interface PageResponseUserResponse {
  /** 当前页码 */
  page_num?: number;
  /** 每页数量 */
  page_size?: number;
  /** 总记录数 */
  total?: number;
  /** 分页数据 */
  items?: UserResponse[];
}

/**
 * 修改密码请求
 */
export interface PasswordChange {
  /**
   * 旧密码
   * @minLength 6
   * @maxLength 128
   */
  old_password: string;
  /**
   * 新密码
   * @minLength 6
   * @maxLength 128
   */
  new_password: string;
}

/**
 * 更新列类型请求
 */
export interface RawDataColumnUpdate {
  /** 列结构列表（支持修正类型） */
  columns: ColumnSchema[];
}

/**
 * 数据对象描述
 */
export type RawDataCreateDescription = string | null;

/**
 * 数据库表配置（raw_type=database_table 时必填）
 */
export type RawDataCreateDatabaseTableConfig = RawDataDatabaseTableConfig | null;

/**
 * 文件配置（raw_type=file 时必填）
 */
export type RawDataCreateFileConfig = RawDataFileConfig | null;

/**
 * 创建数据对象请求
 */
export interface RawDataCreate {
  /**
   * 数据对象名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 数据对象描述 */
  description?: RawDataCreateDescription;
  /** 数据对象类型: database_table/file */
  raw_type: RawDataType;
  /** 数据库表配置（raw_type=database_table 时必填） */
  database_table_config?: RawDataCreateDatabaseTableConfig;
  /** 文件配置（raw_type=file 时必填） */
  file_config?: RawDataCreateFileConfig;
}

/**
 * Schema名称
 */
export type RawDataDatabaseTableConfigSchemaName = string | null;

/**
 * 表名
 */
export type RawDataDatabaseTableConfigTableName = string | null;

/**
 * 自定义SQL查询（可选）
 */
export type RawDataDatabaseTableConfigCustomSql = string | null;

/**
 * 数据库表类型配置
 */
export interface RawDataDatabaseTableConfig {
  /** 数据库连接ID */
  connection_id: string;
  /** Schema名称 */
  schema_name?: RawDataDatabaseTableConfigSchemaName;
  /** 表名 */
  table_name?: RawDataDatabaseTableConfigTableName;
  /** 自定义SQL查询（可选） */
  custom_sql?: RawDataDatabaseTableConfigCustomSql;
}

/**
 * 文件类型配置
 */
export interface RawDataFileConfig {
  /** 上传文件ID */
  file_id: string;
}

/**
 * 自动创建的 RawData 简要信息
 */
export interface RawDataInfo {
  /** RawData ID */
  id: string;
  /** RawData 名称 */
  name: string;
  /** 状态 */
  status: string;
}

/**
 * 数据对象预览请求
 */
export interface RawDataPreviewRequest {
  /**
   * 预览行数
   * @minimum 1
   * @maximum 1000
   */
  limit?: number;
}

export type RawDataPreviewResponseRowsItem = { [key: string]: unknown };

/**
 * 总行数（估算）
 */
export type RawDataPreviewResponseTotalRows = number | null;

/**
 * 数据对象预览响应
 */
export interface RawDataPreviewResponse {
  /** 列结构 */
  columns?: ColumnSchema[];
  /** 数据行 */
  rows?: RawDataPreviewResponseRowsItem[];
  /** 总行数（估算） */
  total_rows?: RawDataPreviewResponseTotalRows;
  /** 预览时间 */
  preview_at: string;
}

/**
 * 数据对象描述
 */
export type RawDataResponseDescription = string | null;

/**
 * 数据库连接ID
 */
export type RawDataResponseConnectionId = string | null;

/**
 * Schema名称
 */
export type RawDataResponseSchemaName = string | null;

/**
 * 表名
 */
export type RawDataResponseTableName = string | null;

/**
 * 自定义SQL
 */
export type RawDataResponseCustomSql = string | null;

/**
 * 上传文件ID
 */
export type RawDataResponseFileId = string | null;

/**
 * 列结构信息
 */
export type RawDataResponseColumnsSchema = ColumnSchema[] | null;

/**
 * 估算行数
 */
export type RawDataResponseRowCountEstimate = number | null;

/**
 * 最后同步时间
 */
export type RawDataResponseSyncedAt = string | null;

/**
 * 错误信息
 */
export type RawDataResponseErrorMessage = string | null;

/**
 * 创建时间
 */
export type RawDataResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type RawDataResponseUpdateTime = string | null;

/**
 * 数据对象响应
 */
export interface RawDataResponse {
  /**
   * 数据对象名称
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 数据对象描述 */
  description?: RawDataResponseDescription;
  /** 数据对象类型: database_table/file */
  raw_type: RawDataType;
  /** 数据对象ID */
  id: string;
  /** 所属用户ID */
  user_id: string;
  /** 数据库连接ID */
  connection_id?: RawDataResponseConnectionId;
  /** Schema名称 */
  schema_name?: RawDataResponseSchemaName;
  /** 表名 */
  table_name?: RawDataResponseTableName;
  /** 自定义SQL */
  custom_sql?: RawDataResponseCustomSql;
  /** 上传文件ID */
  file_id?: RawDataResponseFileId;
  /** 列结构信息 */
  columns_schema?: RawDataResponseColumnsSchema;
  /** 估算行数 */
  row_count_estimate?: RawDataResponseRowCountEstimate;
  /** 最后同步时间 */
  synced_at?: RawDataResponseSyncedAt;
  /** 状态: pending/syncing/ready/error */
  status?: string;
  /** 错误信息 */
  error_message?: RawDataResponseErrorMessage;
  /** 创建时间 */
  create_time?: RawDataResponseCreateTime;
  /** 更新时间 */
  update_time?: RawDataResponseUpdateTime;
}

/**
 * 数据对象类型
 */
export type RawDataType = typeof RawDataType[keyof typeof RawDataType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RawDataType = {
  database_table: 'database_table',
  file: 'file',
} as const;

/**
 * 数据对象名称
 */
export type RawDataUpdateName = string | null;

/**
 * 数据对象描述
 */
export type RawDataUpdateDescription = string | null;

/**
 * 数据库表配置
 */
export type RawDataUpdateDatabaseTableConfig = RawDataDatabaseTableConfig | null;

/**
 * 文件配置
 */
export type RawDataUpdateFileConfig = RawDataFileConfig | null;

/**
 * 更新数据对象请求
 */
export interface RawDataUpdate {
  /** 数据对象名称 */
  name?: RawDataUpdateName;
  /** 数据对象描述 */
  description?: RawDataUpdateDescription;
  /** 数据库表配置 */
  database_table_config?: RawDataUpdateDatabaseTableConfig;
  /** 文件配置 */
  file_config?: RawDataUpdateFileConfig;
}

/**
 * 数据对象名称
 */
export type RawMappingResponseRawDataName = string | null;

/**
 * 字段映射
 */
export type RawMappingResponseFieldMappings = {[key: string]: string | null};

/**
 * Raw 映射响应
 */
export interface RawMappingResponse {
  /** 映射ID */
  id: string;
  /** 数据对象ID */
  raw_data_id: string;
  /** 数据对象名称 */
  raw_data_name?: RawMappingResponseRawDataName;
  /** 字段映射 */
  field_mappings?: RawMappingResponseFieldMappings;
  /** 优先级 */
  priority?: number;
  /** 是否启用 */
  is_enabled?: boolean;
}

/**
 * 刷新令牌请求
 */
export interface RefreshTokenRequest {
  /** 刷新令牌 */
  refresh_token: string;
}

/**
 * 字段映射建议请求
 */
export interface SuggestMappingsRequest {
  /**
   * 目标字段列表
   * @minItems 1
   */
  target_fields: TargetField[];
  /**
   * 数据对象ID列表
   * @minItems 1
   */
  raw_data_ids: string[];
}

/**
 * 字段映射建议响应
 */
export interface SuggestMappingsResponse {
  /** 字段映射建议列表 */
  suggestions?: FieldMappingSuggestionResponse[];
}

/**
 * 从数据对象推断目标字段请求
 */
export interface SuggestTargetFieldsRequest {
  /**
   * 数据对象ID列表
   * @minItems 1
   */
  raw_data_ids: string[];
}

/**
 * 推断目标字段响应
 */
export interface SuggestTargetFieldsResponse {
  /** 推荐的目标字段列表 */
  fields?: SuggestedTargetField[];
}

/**
 * 字段描述
 */
export type SuggestedTargetFieldDescription = string | null;

/**
 * 推荐的目标字段
 */
export interface SuggestedTargetField {
  /** 字段名 */
  name: string;
  /** 数据类型 */
  data_type: string;
  /** 字段描述 */
  description?: SuggestedTargetFieldDescription;
  /** 出现在多少个数据源中 */
  source_count?: number;
}

/**
 * 列注释
 */
export type TableColumnInfoComment = string | null;

/**
 * 数据库表的列信息
 */
export interface TableColumnInfo {
  /** 列名 */
  name: string;
  /** 数据类型 */
  data_type: string;
  /** 是否可空 */
  nullable?: boolean;
  /** 是否主键 */
  primary_key?: boolean;
  /** 列注释 */
  comment?: TableColumnInfoComment;
}

/**
 * Schema 名称
 */
export type TableSelectionSchemaName = string | null;

/**
 * 自定义显示名称（可选）
 */
export type TableSelectionCustomName = string | null;

/**
 * 表选择
 */
export interface TableSelection {
  /** Schema 名称 */
  schema_name?: TableSelectionSchemaName;
  /**
   * 表名
   * @minLength 1
   * @maxLength 255
   */
  table_name: string;
  /** 自定义显示名称（可选） */
  custom_name?: TableSelectionCustomName;
}

/**
 * 字段描述
 */
export type TargetFieldDescription = string | null;

/**
 * 目标字段定义
 */
export interface TargetField {
  /**
   * 字段名
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /** 数据类型 */
  data_type: string;
  /** 字段描述 */
  description?: TargetFieldDescription;
}

export type TaskRecommendationResponseDescription = string | null;

export type TaskRecommendationResponseTriggerMessageId = string | null;

/**
 * 推荐响应
 */
export interface TaskRecommendationResponse {
  id: string;
  session_id: string;
  title: string;
  description: TaskRecommendationResponseDescription;
  category: string;
  source_type: string;
  priority: number;
  status: string;
  trigger_message_id: TaskRecommendationResponseTriggerMessageId;
  create_time: string;
  update_time: string;
}

/**
 * 更新推荐
 */
export interface TaskRecommendationUpdate {
  /** 状态：pending/selected/dismissed */
  status: string;
}

/**
 * Token基础数据
 */
export interface Token {
  id: string;
  nickname: string;
  access_token: string;
  refresh_token: string;
  token_type?: string;
}

/**
 * MIME类型
 */
export type UploadedFileResponseMimeType = string | null;

/**
 * 数据行数
 */
export type UploadedFileResponseRowCount = number | null;

/**
 * 数据列数
 */
export type UploadedFileResponseColumnCount = number | null;

export type UploadedFileResponseColumnsInfoAnyOfItem = { [key: string]: unknown };

/**
 * 列信息
 */
export type UploadedFileResponseColumnsInfo = UploadedFileResponseColumnsInfoAnyOfItem[] | null;

/**
 * 错误信息
 */
export type UploadedFileResponseErrorMessage = string | null;

/**
 * 创建时间
 */
export type UploadedFileResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type UploadedFileResponseUpdateTime = string | null;

/**
 * 上传文件响应
 */
export interface UploadedFileResponse {
  /** 文件ID */
  id: string;
  /** 上传用户ID */
  user_id: string;
  /** 原始文件名 */
  original_name: string;
  /** MinIO对象存储Key */
  object_key: string;
  file_type: FileType;
  /** 文件大小(字节) */
  file_size: number;
  /** MIME类型 */
  mime_type?: UploadedFileResponseMimeType;
  /** 数据行数 */
  row_count?: UploadedFileResponseRowCount;
  /** 数据列数 */
  column_count?: UploadedFileResponseColumnCount;
  /** 列信息 */
  columns_info?: UploadedFileResponseColumnsInfo;
  /** 处理状态 */
  status: string;
  /** 错误信息 */
  error_message?: UploadedFileResponseErrorMessage;
  /** 创建时间 */
  create_time?: UploadedFileResponseCreateTime;
  /** 更新时间 */
  update_time?: UploadedFileResponseUpdateTime;
}

/**
 * MIME类型
 */
export type UploadedFileWithRawDataResponseMimeType = string | null;

/**
 * 数据行数
 */
export type UploadedFileWithRawDataResponseRowCount = number | null;

/**
 * 数据列数
 */
export type UploadedFileWithRawDataResponseColumnCount = number | null;

export type UploadedFileWithRawDataResponseColumnsInfoAnyOfItem = { [key: string]: unknown };

/**
 * 列信息
 */
export type UploadedFileWithRawDataResponseColumnsInfo = UploadedFileWithRawDataResponseColumnsInfoAnyOfItem[] | null;

/**
 * 错误信息
 */
export type UploadedFileWithRawDataResponseErrorMessage = string | null;

/**
 * 创建时间
 */
export type UploadedFileWithRawDataResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type UploadedFileWithRawDataResponseUpdateTime = string | null;

/**
 * 自动创建的 RawData
 */
export type UploadedFileWithRawDataResponseAutoRawData = RawDataInfo | null;

/**
 * 上传文件响应（含自动创建的 RawData）
 */
export interface UploadedFileWithRawDataResponse {
  /** 文件ID */
  id: string;
  /** 上传用户ID */
  user_id: string;
  /** 原始文件名 */
  original_name: string;
  /** MinIO对象存储Key */
  object_key: string;
  file_type: FileType;
  /** 文件大小(字节) */
  file_size: number;
  /** MIME类型 */
  mime_type?: UploadedFileWithRawDataResponseMimeType;
  /** 数据行数 */
  row_count?: UploadedFileWithRawDataResponseRowCount;
  /** 数据列数 */
  column_count?: UploadedFileWithRawDataResponseColumnCount;
  /** 列信息 */
  columns_info?: UploadedFileWithRawDataResponseColumnsInfo;
  /** 处理状态 */
  status: string;
  /** 错误信息 */
  error_message?: UploadedFileWithRawDataResponseErrorMessage;
  /** 创建时间 */
  create_time?: UploadedFileWithRawDataResponseCreateTime;
  /** 更新时间 */
  update_time?: UploadedFileWithRawDataResponseUpdateTime;
  /** 自动创建的 RawData */
  auto_raw_data?: UploadedFileWithRawDataResponseAutoRawData;
}

/**
 * 创建用户请求
 */
export interface UserCreate {
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** 邮箱 */
  email: string;
  /**
   * 昵称
   * @minLength 1
   * @maxLength 50
   */
  nickname: string;
  /**
   * 密码
   * @minLength 6
   * @maxLength 128
   */
  password: string;
  /** 是否激活 */
  is_active?: boolean;
  /** 是否超级管理员 */
  is_superuser?: boolean;
}

/**
 * 创建时间
 */
export type UserResponseCreateTime = string | null;

/**
 * 更新时间
 */
export type UserResponseUpdateTime = string | null;

/**
 * 用户响应
 */
export interface UserResponse {
  /**
   * 用户名
   * @minLength 3
   * @maxLength 50
   */
  username: string;
  /** 邮箱 */
  email: string;
  /**
   * 昵称
   * @minLength 1
   * @maxLength 50
   */
  nickname: string;
  /** 用户ID */
  id: string;
  /** 是否激活 */
  is_active: boolean;
  /** 是否超级管理员 */
  is_superuser: boolean;
  /** 创建时间 */
  create_time?: UserResponseCreateTime;
  /** 更新时间 */
  update_time?: UserResponseUpdateTime;
}

/**
 * 邮箱
 */
export type UserUpdateEmail = string | null;

/**
 * 昵称
 */
export type UserUpdateNickname = string | null;

/**
 * 是否激活
 */
export type UserUpdateIsActive = boolean | null;

/**
 * 是否超级管理员
 */
export type UserUpdateIsSuperuser = boolean | null;

/**
 * 更新用户请求
 */
export interface UserUpdate {
  /** 邮箱 */
  email?: UserUpdateEmail;
  /** 昵称 */
  nickname?: UserUpdateNickname;
  /** 是否激活 */
  is_active?: UserUpdateIsActive;
  /** 是否超级管理员 */
  is_superuser?: UserUpdateIsSuperuser;
}

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type GetUsersApiV1UsersGetParams = {
/**
 * @minimum 1
 */
page_num?: number;
/**
 * @minimum 1
 */
page_size?: number;
keyword?: string | null;
is_active?: boolean | null;
is_superuser?: boolean | null;
};

export type GetConnectionsApiV1DatabaseConnectionsGetParams = {
keyword?: string | null;
db_type?: string | null;
/**
 * @minimum 1
 */
page_num?: number;
/**
 * @minimum 1
 */
page_size?: number;
};

export type CreateConnectionApiV1DatabaseConnectionsPostParams = {
auto_create_raw_data?: boolean;
auto_sync_raw_data?: boolean;
max_auto_tables?: number;
};

export type GetConnectionTableSchemaApiV1DatabaseConnectionsConnectionIdSchemaGetParams = {
schema_name?: string | null;
table_name?: string | null;
};

export type GetRawDataListApiV1RawDataGetParams = {
/**
 * @minimum 1
 */
page_num?: number;
/**
 * @minimum 1
 */
page_size?: number;
keyword?: string | null;
raw_type?: RawDataType | null;
status?: string | null;
};

export type PreviewRawDataApiV1RawDataRawDataIdPreviewPostBody = RawDataPreviewRequest | null;

export type GetDataSourcesApiV1DataSourcesGetParams = {
/**
 * @minimum 1
 */
page_num?: number;
/**
 * @minimum 1
 */
page_size?: number;
keyword?: string | null;
category?: DataSourceCategory | null;
};

export type PreviewDataSourceApiV1DataSourcesDataSourceIdPreviewPostBody = DataSourcePreviewRequest | null;

export type GetFilesApiV1FilesGetParams = {
/**
 * @minimum 1
 */
page_num?: number;
/**
 * @minimum 1
 */
page_size?: number;
keyword?: string | null;
file_type?: FileType | null;
status?: string | null;
};

export type UploadFileApiV1FilesUploadPostParams = {
auto_create_raw_data?: boolean;
};

export type GetFilePreviewApiV1FilesFileIdPreviewGetParams = {
rows?: number;
};

export type GetDownloadUrlApiV1FilesFileIdDownloadUrlGetParams = {
expires?: number;
};

export type GetSessionsApiV1SessionsGetParams = {
/**
 * @minimum 1
 */
page_num?: number;
/**
 * @minimum 1
 */
page_size?: number;
keyword?: string | null;
status?: string | null;
};

export type GetMessagesApiV1SessionsSessionIdMessagesGetParams = {
/**
 * @minimum 1
 */
page_num?: number;
/**
 * @minimum 1
 */
page_size?: number;
};

export type GetRecommendationsApiV1SessionsSessionIdRecommendationsGetParams = {
status_filter?: string | null;
source_type?: string | null;
/**
 * @minimum 1
 */
page_num?: number;
/**
 * @minimum 1
 */
page_size?: number;
};

export type GenerateRecommendationsApiV1SessionsSessionIdRecommendationsPostBody = GenerateRecommendationsRequest | null;

export type DismissAllRecommendationsApiV1SessionsSessionIdRecommendationsDeleteParams = {
source_type?: string | null;
};

/**
 * 根路径，健康检查
 * @summary Root
 */
export const rootGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/`,options
    );
  }

/**
 * 健康检查接口
 * @summary Health Check
 */
export const healthCheckHealthGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/health`,options
    );
  }

/**
 * 用户登录
 * @summary Login
 */
export const loginApiV1AuthLoginPost = <TData = AxiosResponse<BaseResponseToken>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/login`,
      loginRequest,options
    );
  }

/**
 * 刷新访问令牌
 * @summary Refresh Token
 */
export const refreshTokenApiV1AuthRefreshPost = <TData = AxiosResponse<BaseResponseToken>>(
    refreshTokenRequest: RefreshTokenRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/refresh`,
      refreshTokenRequest,options
    );
  }

/**
 * 用户注册
 * @summary Register
 */
export const registerApiV1AuthRegisterPost = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/register`,
      userCreate,options
    );
  }

/**
 * 获取当前登录用户信息
 * @summary Get Current User Info
 */
export const getCurrentUserInfoApiV1AuthMeGet = <TData = AxiosResponse<BaseResponseUserResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/auth/me`,options
    );
  }

/**
 * 更新当前登录用户信息
 * @summary Update Current User
 */
export const updateCurrentUserApiV1AuthMePut = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/auth/me`,
      userUpdate,options
    );
  }

/**
 * 修改密码
 * @summary Change Password
 */
export const changePasswordApiV1AuthChangePasswordPost = <TData = AxiosResponse<BaseResponseNoneType>>(
    passwordChange: PasswordChange, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/auth/change-password`,
      passwordChange,options
    );
  }

/**
 * 获取用户列表（分页）- 需要超级管理员权限
 * @summary Get Users
 */
export const getUsersApiV1UsersGet = <TData = AxiosResponse<BaseResponsePageResponseUserResponse>>(
    params?: GetUsersApiV1UsersGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 创建新用户 - 需要超级管理员权限
 * @summary Create User
 */
export const createUserApiV1UsersPost = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userCreate: UserCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/users`,
      userCreate,options
    );
  }

/**
 * 获取单个用户详情 - 需要超级管理员权限
 * @summary Get User
 */
export const getUserApiV1UsersUserIdGet = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/users/${userId}`,options
    );
  }

/**
 * 更新用户信息 - 需要超级管理员权限
 * @summary Update User
 */
export const updateUserApiV1UsersUserIdPut = <TData = AxiosResponse<BaseResponseUserResponse>>(
    userId: string,
    userUpdate: UserUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/users/${userId}`,
      userUpdate,options
    );
  }

/**
 * 删除用户（逻辑删除）- 需要超级管理员权限
 * @summary Delete User
 */
export const deleteUserApiV1UsersUserIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
    userId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/users/${userId}`,options
    );
  }

/**
 * 获取数据库连接列表（分页）
 * @summary Get Connections
 */
export const getConnectionsApiV1DatabaseConnectionsGet = <TData = AxiosResponse<BaseResponsePageResponseDatabaseConnectionResponse>>(
    params?: GetConnectionsApiV1DatabaseConnectionsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/database-connections`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 创建数据库连接
 * @summary Create Connection
 */
export const createConnectionApiV1DatabaseConnectionsPost = <TData = AxiosResponse<BaseResponseDatabaseConnectionWithRawResponse>>(
    databaseConnectionCreate: DatabaseConnectionCreate,
    params?: CreateConnectionApiV1DatabaseConnectionsPostParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/database-connections`,
      databaseConnectionCreate,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 获取单个数据库连接详情
 * @summary Get Connection
 */
export const getConnectionApiV1DatabaseConnectionsConnectionIdGet = <TData = AxiosResponse<BaseResponseDatabaseConnectionResponse>>(
    connectionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/database-connections/${connectionId}`,options
    );
  }

/**
 * 更新数据库连接
 * @summary Update Connection
 */
export const updateConnectionApiV1DatabaseConnectionsConnectionIdPut = <TData = AxiosResponse<BaseResponseDatabaseConnectionResponse>>(
    connectionId: string,
    databaseConnectionUpdate: DatabaseConnectionUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/database-connections/${connectionId}`,
      databaseConnectionUpdate,options
    );
  }

/**
 * 删除数据库连接
 * @summary Delete Connection
 */
export const deleteConnectionApiV1DatabaseConnectionsConnectionIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
    connectionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/database-connections/${connectionId}`,options
    );
  }

/**
 * 测试数据库连接
 * @summary Test Connection
 */
export const testConnectionApiV1DatabaseConnectionsConnectionIdTestPost = <TData = AxiosResponse<BaseResponseDatabaseConnectionTestResult>>(
    connectionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/database-connections/${connectionId}/test`,undefined,options
    );
  }

/**
 * 获取数据库连接的表列表
 * @summary Get Connection Tables
 */
export const getConnectionTablesApiV1DatabaseConnectionsConnectionIdTablesGet = <TData = AxiosResponse<BaseResponseDatabaseConnectionTablesResponse>>(
    connectionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/database-connections/${connectionId}/tables`,options
    );
  }

/**
 * 获取指定表的列结构
 * @summary Get Connection Table Schema
 */
export const getConnectionTableSchemaApiV1DatabaseConnectionsConnectionIdSchemaGet = <TData = AxiosResponse<BaseResponseDatabaseTableSchemaResponse>>(
    connectionId: string,
    params?: GetConnectionTableSchemaApiV1DatabaseConnectionsConnectionIdSchemaGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/database-connections/${connectionId}/schema`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 获取数据对象列表（分页）
 * @summary Get Raw Data List
 */
export const getRawDataListApiV1RawDataGet = <TData = AxiosResponse<BaseResponsePageResponseRawDataResponse>>(
    params?: GetRawDataListApiV1RawDataGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/raw-data`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 创建数据对象
 * @summary Create Raw Data
 */
export const createRawDataApiV1RawDataPost = <TData = AxiosResponse<BaseResponseRawDataResponse>>(
    rawDataCreate: RawDataCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/raw-data`,
      rawDataCreate,options
    );
  }

/**
 * 获取单个数据对象详情
 * @summary Get Raw Data
 */
export const getRawDataApiV1RawDataRawDataIdGet = <TData = AxiosResponse<BaseResponseRawDataResponse>>(
    rawDataId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/raw-data/${rawDataId}`,options
    );
  }

/**
 * 更新数据对象
 * @summary Update Raw Data
 */
export const updateRawDataApiV1RawDataRawDataIdPut = <TData = AxiosResponse<BaseResponseRawDataResponse>>(
    rawDataId: string,
    rawDataUpdate: RawDataUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/raw-data/${rawDataId}`,
      rawDataUpdate,options
    );
  }

/**
 * 删除数据对象
 * @summary Delete Raw Data
 */
export const deleteRawDataApiV1RawDataRawDataIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
    rawDataId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/raw-data/${rawDataId}`,options
    );
  }

/**
 * 从数据库连接批量创建数据对象

用户可以一次性从一个数据库连接中选择多个表创建数据对象
 * @summary Batch Create Raw Data
 */
export const batchCreateRawDataApiV1RawDataBatchFromConnectionPost = <TData = AxiosResponse<BaseResponseBatchCreateFromConnectionResponse>>(
    batchCreateFromConnectionRequest: BatchCreateFromConnectionRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/raw-data/batch-from-connection`,
      batchCreateFromConnectionRequest,options
    );
  }

/**
 * 更新数据对象列类型（用户修正）
 * @summary Update Raw Data Columns
 */
export const updateRawDataColumnsApiV1RawDataRawDataIdColumnsPut = <TData = AxiosResponse<BaseResponseRawDataResponse>>(
    rawDataId: string,
    rawDataColumnUpdate: RawDataColumnUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/raw-data/${rawDataId}/columns`,
      rawDataColumnUpdate,options
    );
  }

/**
 * 预览数据对象（抽样）

从数据库表或文件中抽样数据，并推断列类型
 * @summary Preview Raw Data
 */
export const previewRawDataApiV1RawDataRawDataIdPreviewPost = <TData = AxiosResponse<BaseResponseRawDataPreviewResponse>>(
    rawDataId: string,
    previewRawDataApiV1RawDataRawDataIdPreviewPostBody: PreviewRawDataApiV1RawDataRawDataIdPreviewPostBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/raw-data/${rawDataId}/preview`,
      previewRawDataApiV1RawDataRawDataIdPreviewPostBody,options
    );
  }

/**
 * 同步数据对象 Schema

从数据源获取最新的列结构信息
 * @summary Sync Raw Data
 */
export const syncRawDataApiV1RawDataRawDataIdSyncPost = <TData = AxiosResponse<BaseResponseRawDataResponse>>(
    rawDataId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/raw-data/${rawDataId}/sync`,undefined,options
    );
  }

/**
 * 获取数据源列表（分页）
 * @summary Get Data Sources
 */
export const getDataSourcesApiV1DataSourcesGet = <TData = AxiosResponse<BaseResponsePageResponseDataSourceResponse>>(
    params?: GetDataSourcesApiV1DataSourcesGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/data-sources`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 创建数据源
 * @summary Create Data Source
 */
export const createDataSourceApiV1DataSourcesPost = <TData = AxiosResponse<BaseResponseDataSourceResponse>>(
    dataSourceCreate: DataSourceCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/data-sources`,
      dataSourceCreate,options
    );
  }

/**
 * 获取单个数据源详情（包含映射信息）
 * @summary Get Data Source
 */
export const getDataSourceApiV1DataSourcesDataSourceIdGet = <TData = AxiosResponse<BaseResponseDataSourceResponse>>(
    dataSourceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/data-sources/${dataSourceId}`,options
    );
  }

/**
 * 更新数据源
 * @summary Update Data Source
 */
export const updateDataSourceApiV1DataSourcesDataSourceIdPut = <TData = AxiosResponse<BaseResponseDataSourceResponse>>(
    dataSourceId: string,
    dataSourceUpdate: DataSourceUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/data-sources/${dataSourceId}`,
      dataSourceUpdate,options
    );
  }

/**
 * 删除数据源
 * @summary Delete Data Source
 */
export const deleteDataSourceApiV1DataSourcesDataSourceIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
    dataSourceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/data-sources/${dataSourceId}`,options
    );
  }

/**
 * 预览数据源（合并后的数据）

根据字段映射，从各 RawData 获取数据并合并展示
 * @summary Preview Data Source
 */
export const previewDataSourceApiV1DataSourcesDataSourceIdPreviewPost = <TData = AxiosResponse<BaseResponseDataSourcePreviewResponse>>(
    dataSourceId: string,
    previewDataSourceApiV1DataSourcesDataSourceIdPreviewPostBody: PreviewDataSourceApiV1DataSourcesDataSourceIdPreviewPostBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/data-sources/${dataSourceId}/preview`,
      previewDataSourceApiV1DataSourcesDataSourceIdPreviewPostBody,options
    );
  }

/**
 * 智能字段映射建议

根据目标字段和数据对象的列信息，推荐最佳的字段映射关系。
基于字段名相似度、同义词匹配和数据类型兼容性进行匹配。
 * @summary Suggest Field Mappings
 */
export const suggestFieldMappingsApiV1DataSourcesSuggestMappingsPost = <TData = AxiosResponse<BaseResponseSuggestMappingsResponse>>(
    suggestMappingsRequest: SuggestMappingsRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/data-sources/suggest-mappings`,
      suggestMappingsRequest,options
    );
  }

/**
 * 从数据对象推断目标字段

分析多个 RawData 的列结构，合并推断出最佳的目标字段定义。
 * @summary Suggest Target Fields
 */
export const suggestTargetFieldsApiV1DataSourcesSuggestTargetFieldsPost = <TData = AxiosResponse<BaseResponseSuggestTargetFieldsResponse>>(
    suggestTargetFieldsRequest: SuggestTargetFieldsRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/data-sources/suggest-target-fields`,
      suggestTargetFieldsRequest,options
    );
  }

/**
 * 刷新数据源 Schema

重新从各 RawData 获取列信息并更新 schema_cache
 * @summary Refresh Data Source Schema
 */
export const refreshDataSourceSchemaApiV1DataSourcesDataSourceIdRefreshSchemaPost = <TData = AxiosResponse<BaseResponseDataSourceResponse>>(
    dataSourceId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/data-sources/${dataSourceId}/refresh-schema`,undefined,options
    );
  }

/**
 * 获取文件列表（分页）
 * @summary Get Files
 */
export const getFilesApiV1FilesGet = <TData = AxiosResponse<BaseResponsePageResponseUploadedFileResponse>>(
    params?: GetFilesApiV1FilesGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/files`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 获取单个文件详情
 * @summary Get File
 */
export const getFileApiV1FilesFileIdGet = <TData = AxiosResponse<BaseResponseUploadedFileResponse>>(
    fileId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/files/${fileId}`,options
    );
  }

/**
 * 删除文件
 * @summary Delete File
 */
export const deleteFileApiV1FilesFileIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
    fileId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/files/${fileId}`,options
    );
  }

/**
 * 上传文件

自动创建对应的 RawData（可通过 auto_create_raw_data 参数控制）
 * @summary Upload File
 */
export const uploadFileApiV1FilesUploadPost = <TData = AxiosResponse<BaseResponseUploadedFileWithRawDataResponse>>(
    bodyUploadFileApiV1FilesUploadPost: BodyUploadFileApiV1FilesUploadPost,
    params?: UploadFileApiV1FilesUploadPostParams, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append(`file`, bodyUploadFileApiV1FilesUploadPost.file)

    return axios.post(
      `/api/v1/files/upload`,
      formData,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 获取文件预览
 * @summary Get File Preview
 */
export const getFilePreviewApiV1FilesFileIdPreviewGet = <TData = AxiosResponse<BaseResponseFilePreviewResponse>>(
    fileId: string,
    params?: GetFilePreviewApiV1FilesFileIdPreviewGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/files/${fileId}/preview`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 获取文件下载 URL
 * @summary Get Download Url
 */
export const getDownloadUrlApiV1FilesFileIdDownloadUrlGet = <TData = AxiosResponse<BaseResponseStr>>(
    fileId: string,
    params?: GetDownloadUrlApiV1FilesFileIdDownloadUrlGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/files/${fileId}/download-url`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 获取会话列表（分页）
 * @summary Get Sessions
 */
export const getSessionsApiV1SessionsGet = <TData = AxiosResponse<BaseResponsePageResponseAnalysisSessionResponse>>(
    params?: GetSessionsApiV1SessionsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/sessions`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 创建会话
 * @summary Create Session
 */
export const createSessionApiV1SessionsPost = <TData = AxiosResponse<BaseResponseAnalysisSessionResponse>>(
    analysisSessionCreate: AnalysisSessionCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/sessions`,
      analysisSessionCreate,options
    );
  }

/**
 * 获取单个会话详情（包含数据源信息）
 * @summary Get Session
 */
export const getSessionApiV1SessionsSessionIdGet = <TData = AxiosResponse<BaseResponseAnalysisSessionDetail>>(
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/sessions/${sessionId}`,options
    );
  }

/**
 * 更新会话
 * @summary Update Session
 */
export const updateSessionApiV1SessionsSessionIdPut = <TData = AxiosResponse<BaseResponseAnalysisSessionResponse>>(
    sessionId: string,
    analysisSessionUpdate: AnalysisSessionUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/sessions/${sessionId}`,
      analysisSessionUpdate,options
    );
  }

/**
 * 删除会话
 * @summary Delete Session
 */
export const deleteSessionApiV1SessionsSessionIdDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/sessions/${sessionId}`,options
    );
  }

/**
 * 归档会话
 * @summary Archive Session
 */
export const archiveSessionApiV1SessionsSessionIdArchivePost = <TData = AxiosResponse<BaseResponseAnalysisSessionResponse>>(
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/sessions/${sessionId}/archive`,undefined,options
    );
  }

/**
 * 上传文件到会话目录

用于上传临时数据文件供 AI 分析使用。
文件会保存到沙盒的会话目录中。
 * @summary Upload Session File
 */
export const uploadSessionFileApiV1SessionsSessionIdFilesUploadPost = <TData = AxiosResponse<BaseResponseDictStrAny>>(
    sessionId: string,
    bodyUploadSessionFileApiV1SessionsSessionIdFilesUploadPost: BodyUploadSessionFileApiV1SessionsSessionIdFilesUploadPost, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
formData.append(`file`, bodyUploadSessionFileApiV1SessionsSessionIdFilesUploadPost.file)

    return axios.post(
      `/api/v1/sessions/${sessionId}/files/upload`,
      formData,options
    );
  }

/**
 * 列出会话文件

返回会话目录中的所有文件，包括：
- 用户上传的数据文件
- SQL 查询结果的 parquet 缓存
- 生成的图表文件
- 其他分析过程中产生的文件
 * @summary List Session Files
 */
export const listSessionFilesApiV1SessionsSessionIdFilesGet = <TData = AxiosResponse<BaseResponseDictStrAny>>(
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/sessions/${sessionId}/files`,options
    );
  }

/**
 * 下载会话文件

Args:
    session_id: 会话 ID
    filename: 文件名（相对于会话目录的路径）
 * @summary Download Session File
 */
export const downloadSessionFileApiV1SessionsSessionIdFilesFilenameGet = <TData = AxiosResponse<unknown>>(
    sessionId: string,
    filename: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/sessions/${sessionId}/files/${filename}`,options
    );
  }

/**
 * 发送消息并获取 AI 响应（SSE 流式）

兼容 Vercel AI SDK useChat hook，使用 Data Stream Protocol。

## 流协议

使用 SSE `data:` 格式，通过 JSON 的 `type` 字段区分事件类型。

### 消息开始
```
data: {"type":"start","messageId":"msg_xxx"}
```

### 文本流 (start/delta/end 模式)
```
data: {"type":"text-start","id":"text_xxx"}
data: {"type":"text-delta","id":"text_xxx","delta":"你好"}
data: {"type":"text-end","id":"text_xxx"}
```

### 工具调用
```
data: {"type":"tool-input-start","toolCallId":"call_xxx","toolName":"execute_sql"}
data: {"type":"tool-input-available","toolCallId":"call_xxx","toolName":"execute_sql","input":{...}}
```

### 工具结果
```
data: {"type":"tool-output-available","toolCallId":"call_xxx","output":{...},"artifact":{...}}
```

### 步骤控制
```
data: {"type":"start-step"}
data: {"type":"finish-step"}
data: {"type":"finish"}
```

### 错误
```
data: {"type":"error","errorText":"..."}
```

### 流结束
```
data: [DONE]
```

参考: https://ai-sdk.dev/docs/ai-sdk-ui/stream-protocol
 * @summary Chat
 */
export const chatApiV1SessionsSessionIdChatPost = <TData = AxiosResponse<void>>(
    sessionId: string,
    chatMessageCreate: ChatMessageCreate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/sessions/${sessionId}/chat`,
      chatMessageCreate,options
    );
  }

/**
 * 获取会话的历史消息（分页）

返回消息列表，按创建时间升序排列
 * @summary Get Messages
 */
export const getMessagesApiV1SessionsSessionIdMessagesGet = <TData = AxiosResponse<BaseResponsePageResponseChatMessageResponse>>(
    sessionId: string,
    params?: GetMessagesApiV1SessionsSessionIdMessagesGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/sessions/${sessionId}/messages`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 清空会话的所有消息
 * @summary Clear Messages
 */
export const clearMessagesApiV1SessionsSessionIdMessagesDelete = <TData = AxiosResponse<BaseResponseInt>>(
    sessionId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/sessions/${sessionId}/messages`,options
    );
  }

/**
 * 获取会话的推荐列表（分页）
 * @summary Get Recommendations
 */
export const getRecommendationsApiV1SessionsSessionIdRecommendationsGet = <TData = AxiosResponse<BaseResponsePageResponseTaskRecommendationResponse>>(
    sessionId: string,
    params?: GetRecommendationsApiV1SessionsSessionIdRecommendationsGetParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/sessions/${sessionId}/recommendations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 生成初始任务推荐

基于会话关联的数据源 Schema 生成分析任务推荐
 * @summary Generate Recommendations
 */
export const generateRecommendationsApiV1SessionsSessionIdRecommendationsPost = <TData = AxiosResponse<BaseResponseListTaskRecommendationResponse>>(
    sessionId: string,
    generateRecommendationsApiV1SessionsSessionIdRecommendationsPostBody: GenerateRecommendationsApiV1SessionsSessionIdRecommendationsPostBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/sessions/${sessionId}/recommendations`,
      generateRecommendationsApiV1SessionsSessionIdRecommendationsPostBody,options
    );
  }

/**
 * 批量忽略会话中的待选择推荐
 * @summary Dismiss All Recommendations
 */
export const dismissAllRecommendationsApiV1SessionsSessionIdRecommendationsDelete = <TData = AxiosResponse<BaseResponseNoneType>>(
    sessionId: string,
    params?: DismissAllRecommendationsApiV1SessionsSessionIdRecommendationsDeleteParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `/api/v1/sessions/${sessionId}/recommendations`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * 生成追问推荐

基于对话上下文生成追问建议
 * @summary Generate Followup Recommendations
 */
export const generateFollowupRecommendationsApiV1SessionsSessionIdRecommendationsFollowupPost = <TData = AxiosResponse<BaseResponseListTaskRecommendationResponse>>(
    sessionId: string,
    generateFollowupRequest: GenerateFollowupRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/sessions/${sessionId}/recommendations/followup`,
      generateFollowupRequest,options
    );
  }

/**
 * 更新推荐状态
 * @summary Update Recommendation
 */
export const updateRecommendationApiV1SessionsSessionIdRecommendationsRecommendationIdPut = <TData = AxiosResponse<BaseResponseTaskRecommendationResponse>>(
    sessionId: string,
    recommendationId: string,
    taskRecommendationUpdate: TaskRecommendationUpdate, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `/api/v1/sessions/${sessionId}/recommendations/${recommendationId}`,
      taskRecommendationUpdate,options
    );
  }

/**
 * SPA 路由回退，所有非静态资源请求都返回 index.html
 * @summary Serve Spa
 */
export const serveSpaWebFullPathGet = <TData = AxiosResponse<unknown>>(
    fullPath: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/web/${fullPath}`,options
    );
  }

/**
 * SPA 根路径
 * @summary Serve Spa Root
 */
export const serveSpaRootWebGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/web`,options
    );
  }

export type RootGetResult = AxiosResponse<unknown>
export type HealthCheckHealthGetResult = AxiosResponse<unknown>
export type LoginApiV1AuthLoginPostResult = AxiosResponse<BaseResponseToken>
export type RefreshTokenApiV1AuthRefreshPostResult = AxiosResponse<BaseResponseToken>
export type RegisterApiV1AuthRegisterPostResult = AxiosResponse<BaseResponseUserResponse>
export type GetCurrentUserInfoApiV1AuthMeGetResult = AxiosResponse<BaseResponseUserResponse>
export type UpdateCurrentUserApiV1AuthMePutResult = AxiosResponse<BaseResponseUserResponse>
export type ChangePasswordApiV1AuthChangePasswordPostResult = AxiosResponse<BaseResponseNoneType>
export type GetUsersApiV1UsersGetResult = AxiosResponse<BaseResponsePageResponseUserResponse>
export type CreateUserApiV1UsersPostResult = AxiosResponse<BaseResponseUserResponse>
export type GetUserApiV1UsersUserIdGetResult = AxiosResponse<BaseResponseUserResponse>
export type UpdateUserApiV1UsersUserIdPutResult = AxiosResponse<BaseResponseUserResponse>
export type DeleteUserApiV1UsersUserIdDeleteResult = AxiosResponse<BaseResponseNoneType>
export type GetConnectionsApiV1DatabaseConnectionsGetResult = AxiosResponse<BaseResponsePageResponseDatabaseConnectionResponse>
export type CreateConnectionApiV1DatabaseConnectionsPostResult = AxiosResponse<BaseResponseDatabaseConnectionWithRawResponse>
export type GetConnectionApiV1DatabaseConnectionsConnectionIdGetResult = AxiosResponse<BaseResponseDatabaseConnectionResponse>
export type UpdateConnectionApiV1DatabaseConnectionsConnectionIdPutResult = AxiosResponse<BaseResponseDatabaseConnectionResponse>
export type DeleteConnectionApiV1DatabaseConnectionsConnectionIdDeleteResult = AxiosResponse<BaseResponseNoneType>
export type TestConnectionApiV1DatabaseConnectionsConnectionIdTestPostResult = AxiosResponse<BaseResponseDatabaseConnectionTestResult>
export type GetConnectionTablesApiV1DatabaseConnectionsConnectionIdTablesGetResult = AxiosResponse<BaseResponseDatabaseConnectionTablesResponse>
export type GetConnectionTableSchemaApiV1DatabaseConnectionsConnectionIdSchemaGetResult = AxiosResponse<BaseResponseDatabaseTableSchemaResponse>
export type GetRawDataListApiV1RawDataGetResult = AxiosResponse<BaseResponsePageResponseRawDataResponse>
export type CreateRawDataApiV1RawDataPostResult = AxiosResponse<BaseResponseRawDataResponse>
export type GetRawDataApiV1RawDataRawDataIdGetResult = AxiosResponse<BaseResponseRawDataResponse>
export type UpdateRawDataApiV1RawDataRawDataIdPutResult = AxiosResponse<BaseResponseRawDataResponse>
export type DeleteRawDataApiV1RawDataRawDataIdDeleteResult = AxiosResponse<BaseResponseNoneType>
export type BatchCreateRawDataApiV1RawDataBatchFromConnectionPostResult = AxiosResponse<BaseResponseBatchCreateFromConnectionResponse>
export type UpdateRawDataColumnsApiV1RawDataRawDataIdColumnsPutResult = AxiosResponse<BaseResponseRawDataResponse>
export type PreviewRawDataApiV1RawDataRawDataIdPreviewPostResult = AxiosResponse<BaseResponseRawDataPreviewResponse>
export type SyncRawDataApiV1RawDataRawDataIdSyncPostResult = AxiosResponse<BaseResponseRawDataResponse>
export type GetDataSourcesApiV1DataSourcesGetResult = AxiosResponse<BaseResponsePageResponseDataSourceResponse>
export type CreateDataSourceApiV1DataSourcesPostResult = AxiosResponse<BaseResponseDataSourceResponse>
export type GetDataSourceApiV1DataSourcesDataSourceIdGetResult = AxiosResponse<BaseResponseDataSourceResponse>
export type UpdateDataSourceApiV1DataSourcesDataSourceIdPutResult = AxiosResponse<BaseResponseDataSourceResponse>
export type DeleteDataSourceApiV1DataSourcesDataSourceIdDeleteResult = AxiosResponse<BaseResponseNoneType>
export type PreviewDataSourceApiV1DataSourcesDataSourceIdPreviewPostResult = AxiosResponse<BaseResponseDataSourcePreviewResponse>
export type SuggestFieldMappingsApiV1DataSourcesSuggestMappingsPostResult = AxiosResponse<BaseResponseSuggestMappingsResponse>
export type SuggestTargetFieldsApiV1DataSourcesSuggestTargetFieldsPostResult = AxiosResponse<BaseResponseSuggestTargetFieldsResponse>
export type RefreshDataSourceSchemaApiV1DataSourcesDataSourceIdRefreshSchemaPostResult = AxiosResponse<BaseResponseDataSourceResponse>
export type GetFilesApiV1FilesGetResult = AxiosResponse<BaseResponsePageResponseUploadedFileResponse>
export type GetFileApiV1FilesFileIdGetResult = AxiosResponse<BaseResponseUploadedFileResponse>
export type DeleteFileApiV1FilesFileIdDeleteResult = AxiosResponse<BaseResponseNoneType>
export type UploadFileApiV1FilesUploadPostResult = AxiosResponse<BaseResponseUploadedFileWithRawDataResponse>
export type GetFilePreviewApiV1FilesFileIdPreviewGetResult = AxiosResponse<BaseResponseFilePreviewResponse>
export type GetDownloadUrlApiV1FilesFileIdDownloadUrlGetResult = AxiosResponse<BaseResponseStr>
export type GetSessionsApiV1SessionsGetResult = AxiosResponse<BaseResponsePageResponseAnalysisSessionResponse>
export type CreateSessionApiV1SessionsPostResult = AxiosResponse<BaseResponseAnalysisSessionResponse>
export type GetSessionApiV1SessionsSessionIdGetResult = AxiosResponse<BaseResponseAnalysisSessionDetail>
export type UpdateSessionApiV1SessionsSessionIdPutResult = AxiosResponse<BaseResponseAnalysisSessionResponse>
export type DeleteSessionApiV1SessionsSessionIdDeleteResult = AxiosResponse<BaseResponseNoneType>
export type ArchiveSessionApiV1SessionsSessionIdArchivePostResult = AxiosResponse<BaseResponseAnalysisSessionResponse>
export type UploadSessionFileApiV1SessionsSessionIdFilesUploadPostResult = AxiosResponse<BaseResponseDictStrAny>
export type ListSessionFilesApiV1SessionsSessionIdFilesGetResult = AxiosResponse<BaseResponseDictStrAny>
export type DownloadSessionFileApiV1SessionsSessionIdFilesFilenameGetResult = AxiosResponse<unknown>
export type ChatApiV1SessionsSessionIdChatPostResult = AxiosResponse<void>
export type GetMessagesApiV1SessionsSessionIdMessagesGetResult = AxiosResponse<BaseResponsePageResponseChatMessageResponse>
export type ClearMessagesApiV1SessionsSessionIdMessagesDeleteResult = AxiosResponse<BaseResponseInt>
export type GetRecommendationsApiV1SessionsSessionIdRecommendationsGetResult = AxiosResponse<BaseResponsePageResponseTaskRecommendationResponse>
export type GenerateRecommendationsApiV1SessionsSessionIdRecommendationsPostResult = AxiosResponse<BaseResponseListTaskRecommendationResponse>
export type DismissAllRecommendationsApiV1SessionsSessionIdRecommendationsDeleteResult = AxiosResponse<BaseResponseNoneType>
export type GenerateFollowupRecommendationsApiV1SessionsSessionIdRecommendationsFollowupPostResult = AxiosResponse<BaseResponseListTaskRecommendationResponse>
export type UpdateRecommendationApiV1SessionsSessionIdRecommendationsRecommendationIdPutResult = AxiosResponse<BaseResponseTaskRecommendationResponse>
export type ServeSpaWebFullPathGetResult = AxiosResponse<unknown>
export type ServeSpaRootWebGetResult = AxiosResponse<unknown>
