"""add_seq_to_chat_messages

Revision ID: 1d6fce1b3322
Revises: 2ffbb8090ed3
Create Date: 2025-12-11 12:50:48.331156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d6fce1b3322'
down_revision: Union[str, Sequence[str], None] = '2ffbb8090ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 添加 seq 列（先允许 NULL）
    op.add_column('chat_messages', sa.Column('seq', sa.Integer(), nullable=True, comment='消息序号(会话内递增)'))

    # 2. 为现有数据设置 seq 值（按 session_id 分组，按 create_time 排序）
    op.execute("""
        WITH ranked AS (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY session_id ORDER BY create_time, id) as rn
            FROM chat_messages
        )
        UPDATE chat_messages
        SET seq = ranked.rn
        FROM ranked
        WHERE chat_messages.id = ranked.id
    """)

    # 3. 设置默认值并改为 NOT NULL
    op.alter_column('chat_messages', 'seq',
                    existing_type=sa.Integer(),
                    nullable=False,
                    server_default='0')

    # 4. 创建索引
    op.create_index('ix_chat_messages_session_seq', 'chat_messages', ['session_id', 'seq'], unique=False)
    op.alter_column('data_source_raw_mappings', 'raw_data_id',
               existing_type=sa.UUID(),
               comment='数据对象ID',
               existing_comment='原始数据ID',
               existing_nullable=False)
    op.alter_column('data_source_raw_mappings', 'field_mappings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='字段映射(JSON): {target_field: source_field/expression}',
               existing_comment='字段映射(JSON)',
               existing_nullable=False)
    op.alter_column('data_source_raw_mappings', 'priority',
               existing_type=sa.INTEGER(),
               comment='映射优先级（数值越大优先级越高）',
               existing_comment='映射优先级',
               existing_nullable=False)
    op.alter_column('data_sources', 'target_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='目标字段定义(JSON): [{name, data_type, description}]',
               existing_comment='目标字段定义(JSON)',
               existing_nullable=True)
    op.alter_column('raw_data', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='数据对象名称，如 pg_orders_raw',
               existing_comment='原始数据名称',
               existing_nullable=False)
    op.alter_column('raw_data', 'description',
               existing_type=sa.TEXT(),
               comment='数据对象描述',
               existing_comment='原始数据描述',
               existing_nullable=True)
    op.alter_column('raw_data', 'raw_type',
               existing_type=sa.VARCHAR(length=20),
               comment='数据对象类型: database_table/file',
               existing_comment='原始数据类型: database_table/file',
               existing_nullable=False)
    op.alter_column('raw_data', 'columns_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='列结构信息(JSON): [{name, data_type, nullable, user_type_override}]',
               existing_comment='列结构信息(JSON)',
               existing_nullable=True)
    op.alter_column('raw_data', 'sample_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='预览抽样数据(JSON): {columns, rows}',
               existing_comment='预览抽样数据(JSON)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_data', 'sample_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='预览抽样数据(JSON)',
               existing_comment='预览抽样数据(JSON): {columns, rows}',
               existing_nullable=True)
    op.alter_column('raw_data', 'columns_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='列结构信息(JSON)',
               existing_comment='列结构信息(JSON): [{name, data_type, nullable, user_type_override}]',
               existing_nullable=True)
    op.alter_column('raw_data', 'raw_type',
               existing_type=sa.VARCHAR(length=20),
               comment='原始数据类型: database_table/file',
               existing_comment='数据对象类型: database_table/file',
               existing_nullable=False)
    op.alter_column('raw_data', 'description',
               existing_type=sa.TEXT(),
               comment='原始数据描述',
               existing_comment='数据对象描述',
               existing_nullable=True)
    op.alter_column('raw_data', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='原始数据名称',
               existing_comment='数据对象名称，如 pg_orders_raw',
               existing_nullable=False)
    op.alter_column('data_sources', 'target_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='目标字段定义(JSON)',
               existing_comment='目标字段定义(JSON): [{name, data_type, description}]',
               existing_nullable=True)
    op.alter_column('data_source_raw_mappings', 'priority',
               existing_type=sa.INTEGER(),
               comment='映射优先级',
               existing_comment='映射优先级（数值越大优先级越高）',
               existing_nullable=False)
    op.alter_column('data_source_raw_mappings', 'field_mappings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='字段映射(JSON)',
               existing_comment='字段映射(JSON): {target_field: source_field/expression}',
               existing_nullable=False)
    op.alter_column('data_source_raw_mappings', 'raw_data_id',
               existing_type=sa.UUID(),
               comment='原始数据ID',
               existing_comment='数据对象ID',
               existing_nullable=False)
    op.drop_index('ix_chat_messages_session_seq', table_name='chat_messages')
    op.drop_column('chat_messages', 'seq')
    # ### end Alembic commands ###
