"""init data agent models

Revision ID: 2c9e05c5a5b5
Revises: 
Create Date: 2025-12-03 16:07:47.578623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c9e05c5a5b5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级管理员'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), nullable=False, comment='逻辑删除(0:未删除 1:已删除)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('analysis_sessions',
    sa.Column('name', sa.String(length=100), nullable=False, comment='会话名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='会话描述'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('data_source_ids', postgresql.ARRAY(sa.Integer()), nullable=True, comment='关联的数据源ID列表'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='会话配置(JSON)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='会话状态: active/archived'),
    sa.Column('message_count', sa.Integer(), nullable=False, comment='消息数量'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), nullable=False, comment='逻辑删除(0:未删除 1:已删除)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_sessions_user_id'), 'analysis_sessions', ['user_id'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='原始文件名'),
    sa.Column('stored_name', sa.String(length=255), nullable=False, comment='存储文件名(UUID)'),
    sa.Column('object_key', sa.String(length=500), nullable=False, comment='MinIO对象存储Key'),
    sa.Column('bucket_name', sa.String(length=100), nullable=False, comment='MinIO桶名称'),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='文件类型: csv/excel/json/parquet'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小(字节)'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME类型'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='上传用户ID'),
    sa.Column('row_count', sa.Integer(), nullable=True, comment='数据行数'),
    sa.Column('column_count', sa.Integer(), nullable=True, comment='数据列数'),
    sa.Column('columns_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='列信息(JSON)'),
    sa.Column('preview_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='预览数据(前几行)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='处理状态: pending/processing/ready/error'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), nullable=False, comment='逻辑删除(0:未删除 1:已删除)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='消息角色: user/assistant/system'),
    sa.Column('message_type', sa.String(length=20), nullable=False, comment='消息类型'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='消息额外数据(JSON)'),
    sa.Column('sql_query', sa.Text(), nullable=True, comment='执行的SQL查询'),
    sa.Column('sql_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='SQL执行结果(JSON)'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, comment='执行时间(毫秒)'),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True, comment='工具调用ID'),
    sa.Column('tool_name', sa.String(length=100), nullable=True, comment='工具名称'),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具调用参数(JSON)'),
    sa.Column('tool_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具调用结果(JSON)'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='Prompt Token数'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='Completion Token数'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父消息ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), nullable=False, comment='逻辑删除(0:未删除 1:已删除)'),
    sa.ForeignKeyConstraint(['parent_id'], ['chat_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('name', sa.String(length=100), nullable=False, comment='数据源名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='数据源描述'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='数据源类型: database/file'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID'),
    sa.Column('db_type', sa.String(length=20), nullable=True, comment='数据库类型'),
    sa.Column('host', sa.String(length=255), nullable=True, comment='数据库主机'),
    sa.Column('port', sa.Integer(), nullable=True, comment='数据库端口'),
    sa.Column('database', sa.String(length=100), nullable=True, comment='数据库名'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=255), nullable=True, comment='加密密码'),
    sa.Column('extra_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外连接参数(JSON)'),
    sa.Column('file_id', sa.Integer(), nullable=True, comment='关联的上传文件ID'),
    sa.Column('schema_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='表结构缓存(JSON)'),
    sa.Column('insights', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='数据源记忆(JSON)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), nullable=False, comment='逻辑删除(0:未删除 1:已删除)'),
    sa.ForeignKeyConstraint(['file_id'], ['uploaded_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_user_id'), 'data_sources', ['user_id'], unique=False)
    op.create_table('task_recommendations',
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='推荐任务标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('category', sa.String(length=30), nullable=False, comment='任务分类'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态'),
    sa.Column('trigger_message_id', sa.Integer(), nullable=True, comment='触发推荐的消息ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('update_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted', sa.Integer(), nullable=False, comment='逻辑删除(0:未删除 1:已删除)'),
    sa.ForeignKeyConstraint(['session_id'], ['analysis_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_recommendations_session_id'), 'task_recommendations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_recommendations_session_id'), table_name='task_recommendations')
    op.drop_table('task_recommendations')
    op.drop_index(op.f('ix_data_sources_user_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_analysis_sessions_user_id'), table_name='analysis_sessions')
    op.drop_table('analysis_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
