"""add group_name to data_source

Revision ID: 4946d4143593
Revises: 7e6c860578ec
Create Date: 2025-12-06 10:50:47.881181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4946d4143593'
down_revision: Union[str, Sequence[str], None] = '7e6c860578ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('group_name', sa.String(length=100), nullable=True, comment='数据源分组名称'))
    op.create_index(op.f('ix_data_sources_group_name'), 'data_sources', ['group_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_sources_group_name'), table_name='data_sources')
    op.drop_column('data_sources', 'group_name')
    # ### end Alembic commands ###
