"""add_source_type_and_priority_to_task_recommendation

Revision ID: 7e6c860578ec
Revises: 2c9e05c5a5b5
Create Date: 2025-12-04 10:52:17.382743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e6c860578ec'
down_revision: Union[str, Sequence[str], None] = '2c9e05c5a5b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('message_id', sa.String(length=100), nullable=True, comment='LangChain 消息ID'))
    op.add_column('chat_messages', sa.Column('name', sa.String(length=100), nullable=True, comment='消息名称(可选)'))
    op.add_column('chat_messages', sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具调用列表(JSON)'))
    op.add_column('chat_messages', sa.Column('invalid_tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='无效工具调用列表(JSON)'))
    op.add_column('chat_messages', sa.Column('usage_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Token使用统计(JSON)'))
    op.add_column('chat_messages', sa.Column('artifact', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='工具产出物(JSON)'))
    op.add_column('chat_messages', sa.Column('status', sa.String(length=20), nullable=True, comment='工具执行状态: success/error'))
    op.add_column('chat_messages', sa.Column('additional_kwargs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外参数(JSON)'))
    op.add_column('chat_messages', sa.Column('response_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='响应元数据(JSON)'))
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               comment='消息类型: human/ai/system/tool',
               existing_comment='消息类型',
               existing_nullable=False)
    op.drop_constraint(op.f('chat_messages_parent_id_fkey'), 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'tool_result')
    op.drop_column('chat_messages', 'prompt_tokens')
    op.drop_column('chat_messages', 'role')
    op.drop_column('chat_messages', 'execution_time_ms')
    op.drop_column('chat_messages', 'sql_result')
    op.drop_column('chat_messages', 'sql_query')
    op.drop_column('chat_messages', 'tool_args')
    op.drop_column('chat_messages', 'completion_tokens')
    op.drop_column('chat_messages', 'extra_data')
    op.drop_column('chat_messages', 'tool_name')
    op.drop_column('chat_messages', 'parent_id')
    op.add_column('task_recommendations', sa.Column('source_type', sa.String(length=20), nullable=False, comment='推荐来源类型'))
    op.add_column('task_recommendations', sa.Column('priority', sa.Integer(), nullable=False, comment='优先级（0最高）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_recommendations', 'priority')
    op.drop_column('task_recommendations', 'source_type')
    op.add_column('chat_messages', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='父消息ID'))
    op.add_column('chat_messages', sa.Column('tool_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='工具名称'))
    op.add_column('chat_messages', sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='消息额外数据(JSON)'))
    op.add_column('chat_messages', sa.Column('completion_tokens', sa.INTEGER(), autoincrement=False, nullable=True, comment='Completion Token数'))
    op.add_column('chat_messages', sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='工具调用参数(JSON)'))
    op.add_column('chat_messages', sa.Column('sql_query', sa.TEXT(), autoincrement=False, nullable=True, comment='执行的SQL查询'))
    op.add_column('chat_messages', sa.Column('sql_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='SQL执行结果(JSON)'))
    op.add_column('chat_messages', sa.Column('execution_time_ms', sa.INTEGER(), autoincrement=False, nullable=True, comment='执行时间(毫秒)'))
    op.add_column('chat_messages', sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='消息角色: user/assistant/system'))
    op.add_column('chat_messages', sa.Column('prompt_tokens', sa.INTEGER(), autoincrement=False, nullable=True, comment='Prompt Token数'))
    op.add_column('chat_messages', sa.Column('tool_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='工具调用结果(JSON)'))
    op.create_foreign_key(op.f('chat_messages_parent_id_fkey'), 'chat_messages', 'chat_messages', ['parent_id'], ['id'])
    op.alter_column('chat_messages', 'message_type',
               existing_type=sa.VARCHAR(length=20),
               comment='消息类型',
               existing_comment='消息类型: human/ai/system/tool',
               existing_nullable=False)
    op.drop_column('chat_messages', 'response_metadata')
    op.drop_column('chat_messages', 'additional_kwargs')
    op.drop_column('chat_messages', 'status')
    op.drop_column('chat_messages', 'artifact')
    op.drop_column('chat_messages', 'usage_metadata')
    op.drop_column('chat_messages', 'invalid_tool_calls')
    op.drop_column('chat_messages', 'tool_calls')
    op.drop_column('chat_messages', 'name')
    op.drop_column('chat_messages', 'message_id')
    # ### end Alembic commands ###
